# SQL CARTO QUERY FUNCTION

In [1]:
import ast
import pandas as pd

try:  
    from urllib import urlencode
    from urllib2 import HTTPError
    from urllib2 import urlopen
    from StringIO import StringIO as IO

except ImportError:
    from urllib.parse import urlencode
    from urllib.error import HTTPError
    from urllib.request import urlopen, Request
    from io import BytesIO as IO

In [2]:
SQL_SOURCE = 'https://yl5240.carto.com/api/v2/sql?q='
def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urlencode({'format': format, 'q': query}).encode("utf-8")
    try:
        response = urlopen(source, data)
    except HTTPError as e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [3]:
test = '''
SELECT *
FROM citibike
'''

In [4]:
pd.read_csv(IO(queryCartoDB(test)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,1,1965.0,19217,462,435,351,5960,W 22 St & 10 Ave,W 21 St & 6 Ave,-74.004519,40.746920,-73.994156,40.741740,2015-02-01 20:42:00+00,2015-02-01 20:36:00+00
1,NaN,Subscriber,NaN,1,1971.0,17575,488,167,643,9806,W 39 St & 9 Ave,E 39 St & 3 Ave,-73.993722,40.756458,-73.976049,40.748901,2015-02-03 14:50:00+00,2015-02-03 14:39:00+00
2,NaN,Subscriber,NaN,1,1973.0,20313,440,332,1379,13113,E 45 St & 3 Ave,Cherry St,-73.972826,40.752554,-73.979481,40.712199,2015-02-04 07:30:00+00,2015-02-04 07:07:00+00
3,NaN,Subscriber,NaN,2,1978.0,17131,423,521,801,1,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-01 00:14:00+00,2015-02-01 00:00:00+00
4,NaN,Subscriber,NaN,1,1993.0,21289,504,497,379,2,1 Ave & E 15 St,E 17 St & Broadway,-73.981656,40.732219,-73.990093,40.737050,2015-02-01 00:07:00+00,2015-02-01 00:00:00+00
5,NaN,Subscriber,NaN,2,1969.0,18903,127,281,2474,3,Barrow St & Hudson St,Grand Army Plaza & Central Park S,-74.006744,40.731724,-73.973715,40.764397,2015-02-01 00:42:00+00,2015-02-01 00:01:00+00
6,NaN,Subscriber,NaN,2,1985.0,21044,505,2004,818,4,6 Ave & W 33 St,6 Ave & Broome St,-73.988484,40.749013,-74.004704,40.724399,2015-02-01 00:15:00+00,2015-02-01 00:01:00+00
7,NaN,Subscriber,NaN,1,1957.0,19868,83,323,544,5,Atlantic Ave & Fort Greene Pl,Lawrence St & Willoughby St,-73.976323,40.683826,-73.986317,40.692362,2015-02-01 00:10:00+00,2015-02-01 00:01:00+00
8,NaN,Subscriber,NaN,1,1979.0,15854,2002,373,717,6,Wythe Ave & Metropolitan Ave,Willoughby Ave & Walworth St,-73.963198,40.716887,-73.953820,40.693317,2015-02-01 00:14:00+00,2015-02-01 00:02:00+00
9,NaN,Subscriber,NaN,1,1983.0,15173,504,352,1306,7,1 Ave & E 15 St,W 56 St & 6 Ave,-73.981656,40.732219,-73.977225,40.763406,2015-02-01 00:26:00+00,2015-02-01 00:04:00+00
10,NaN,Subscriber,NaN,1,1955.0,17862,116,439,913,8,W 17 St & 8 Ave,E 4 St & 2 Ave,-74.001497,40.741776,-73.989780,40.726281,2015-02-01 00:19:00+00,2015-02-01 00:04:00+00
11,NaN,Subscriber,NaN,2,1985.0,21183,2012,335,759,9,E 27 St & 1 Ave,Washington Pl & Broadway,-73.976806,40.739445,-73.994046,40.729039,2015-02-01 00:17:00+00,2015-02-01 00:04:00+00
12,NaN,Subscriber,NaN,1,1982.0,14843,444,284,585,10,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
13,NaN,Subscriber,NaN,2,1988.0,16936,444,284,581,11,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
14,NaN,Subscriber,NaN,2,1991.0,21507,472,498,204,12,E 32 St & Park Ave,Broadway & W 32 St,-73.981948,40.745712,-73.988084,40.748549,2015-02-01 00:08:00+00,2015-02-01 00:05:00+00
15,NaN,Subscriber,NaN,2,1982.0,17456,307,368,1169,13,Canal St & Rutgers St,Carmine St & 6 Ave,-73.989900,40.714275,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:07:00+00
16,NaN,Subscriber,NaN,2,1990.0,14679,2012,326,419,14,E 27 St & 1 Ave,E 11 St & 1 Ave,-73.976806,40.739445,-73.984267,40.729538,2015-02-01 00:14:00+00,2015-02-01 00:07:00+00
17,NaN,Subscriber,NaN,1,1977.0,18978,212,285,527,15,W 16 St & The High Line,Broadway & E 14 St,-74.006818,40.743349,-73.990741,40.734546,2015-02-01 00:17:00+00,2015-02-01 00:09:00+00
18,NaN,Subscriber,NaN,1,1968.0,16496,488,368,1013,16,W 39 St & 9 Ave,Carmine St & 6 Ave,-73.993722,40.756458,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:10:00+00
19,NaN,Subscriber,NaN,1,1990.0,17107,331,394,587,17,Pike St & Monroe St,E 9 St & Avenue C,-73.991930,40.711731,-73.977688,40.725213,2015-02-01 00:23:00+00,2015-02-01 00:13:00+00
20,NaN,Subscriber,NaN,1,1987.0,16984,507,326,525,18,E 25 St & 2 Ave,E 11 St & 1 Ave,-73.979738,40.739126,-73.984267,40.729538,2015-02-01 00:22:00+00,2015-02-01 00:13:00+00
21,NaN,Subscriber,NaN,1,1980.0,15997,305,493,670,19,E 58 St & 3 Ave,W 45 St & 6 Ave,-73.967245,40.760958,-73.982912,40.756800,2015-02-01 00:26:00+00,2015-02-01 00:14:00+00
22,NaN,Subscriber,NaN,1,1960.0,21516,223,445,711,20,W 13 St & 7 Ave,E 10 St & Avenue A,-73.999947,40.737815,-73.981420,40.727408,2015-02-01 00:27:00+00,2015-02-01 00:15:00+00
23,NaN,Subscriber,NaN,1,1986.0,15815,457,428,1559,21,Broadway & W 58 St,E 3 St & 1 Ave,-73.981693,40.766953,-73.987834,40.724677,2015-02-01 00:42:00+00,2015-02-01 00:16:00+00
24,NaN,Subscriber,NaN,1,1987.0,18727,477,228,683,22,W 41 St & 8 Ave,E 48 St & 3 Ave,-73.990026,40.756405,-73.971879,40.754601,2015-02-01 00:27:00+00,2015-02-01 00:16:00+00
25,NaN,Subscriber,NaN,1,1969.0,14982,488,513,522,23,W 39 St & 9 Ave,W 56 St & 10 Ave,-73.993722,40.756458,-73.988639,40.768254,2015-02-01 00:24:00+00,2015-02-01 00:16:00+00
26,NaN,Subscriber,NaN,1,1957.0,16391,518,507,389,24,E 39 St & 2 Ave,E 25 St & 2 Ave,-73.973442,40.747804,-73.979738,40.739126,2015-02-01 00:23:00+00,2015-02-01 00:16:00+00
27,NaN,Subscriber,NaN,1,1981.0,15947,473,439,276,25,Rivington St & Chrystie St,E 4 St & 2 Ave,-73.991925,40.721101,-73.989780,40.726281,2015-02-01 00:21:00+00,2015-02-01 00:16:00+00
28,NaN,Subscriber,NaN,1,1993.0,16917,531,128,907,26,Forsyth St & Broome St,MacDougal St & Prince St,-73.992663,40.718939,-74.002971,40.727103,2015-02-01 00:32:00+00,2015-02-01 00:17:00+00
29,NaN,Subscriber,NaN,1,1975.0,15924,528,490,946,27,2 Ave & E 31 St,8 Ave & W 33 St,-73.977061,40.742909,-73.993934,40.751551,2015-02-01 00:33:00+00,2015-02-01 00:18:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,NaN,Subscriber,NaN,1,1988.0,15733,435,335,812,46171,W 21 St & 6 Ave,Washington Pl & Broadway,-73.994156,40.741740,-73.994046,40.729039,2015-02-08 00:05:00+00,2015-02-07 23:51:00+00
46171,NaN,Subscriber,NaN,1,1995.0,16931,504,361,647,46172,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:51:00+00
46172,NaN,Subscriber,NaN,1,1987.0,17202,401,152,563,46173,Allen St & Rivington St,Warren St & Church St,-73.989978,40.720196,-74.009106,40.714740,2015-02-08 00:00:00+00,2015-02-07 23:51:00+00
46173,NaN,Subscriber,NaN,2,1989.0,20314,439,483,470,46174,E 4 St & 2 Ave,E 12 St & 3 Ave,-73.989780,40.726281,-73.988900,40.732233,2015-02-07 23:59:00+00,2015-02-07 23:51:00+00
46174,NaN,Subscriber,NaN,1,1989.0,21531,395,467,299,46175,Bond St & Schermerhorn St,Dean St & 4 Ave,-73.984106,40.688070,-73.978951,40.683125,2015-02-07 23:56:00+00,2015-02-07 23:51:00+00
46175,NaN,Subscriber,NaN,1,1968.0,21491,504,361,629,46176,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:52:00+00
46176,NaN,Subscriber,NaN,1,1990.0,15367,380,402,499,46177,W 4 St & 7 Ave S,Broadway & E 22 St,-74.002939,40.734011,-73.989551,40.740343,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
46177,NaN,Subscriber,NaN,2,1973.0,18978,368,369,474,46178,Carmine St & 6 Ave,Washington Pl & 6 Ave,-74.002150,40.730386,-74.000264,40.732241,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
46178,NaN,Subscriber,NaN,1,1980.0,19507,504,476,345,46179,1 Ave & E 15 St,E 31 St & 3 Ave,-73.981656,40.732219,-73.979661,40.743943,2015-02-07 23:58:00+00,2015-02-07 23:52:00+00
46179,NaN,Subscriber,NaN,1,1980.0,16936,160,499,829,46180,E 37 St & Lexington Ave,Broadway & W 60 St,-73.978311,40.748238,-73.981918,40.769155,2015-02-08 00:07:00+00,2015-02-07 23:53:00+00
46180,NaN,Subscriber,NaN,1,1982.0,18689,531,368,776,46181,Forsyth St & Broome St,Carmine St & 6 Ave,-73.992663,40.718939,-74.002150,40.730386,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
46181,NaN,Subscriber,NaN,1,1972.0,15781,478,520,697,46182,11 Ave & W 41 St,W 52 St & 5 Ave,-73.998842,40.760301,-73.976485,40.759923,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
46182,NaN,Subscriber,NaN,1,1988.0,15081,471,467,1703,46183,Grand St & Havemeyer St,Dean St & 4 Ave,-73.956981,40.712868,-73.978951,40.683125,2015-02-08 00:23:00+00,2015-02-07 23:54:00+00
46183,NaN,Subscriber,NaN,1,1983.0,21672,247,479,922,46184,Perry St & Bleecker St,9 Ave & W 45 St,-74.004831,40.735354,-73.991255,40.760193,2015-02-08 00:10:00+00,2015-02-07 23:54:00+00
46184,NaN,Subscriber,NaN,1,1970.0,16336,488,457,849,46185,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
46185,NaN,Subscriber,NaN,1,1973.0,21609,488,457,826,46186,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
46186,NaN,Subscriber,NaN,1,1964.0,19470,3002,328,473,46187,South End Ave & Liberty St,Watts St & Greenwich St,-74.015756,40.711512,-74.009660,40.724055,2015-02-08 00:02:00+00,2015-02-07 23:54:00+00
46187,NaN,Subscriber,NaN,1,1960.0,18167,450,510,332,46188,W 49 St & 8 Ave,W 51 St & 6 Ave,-73.987882,40.762272,-73.980420,40.760660,2015-02-07 23:59:00+00,2015-02-07 23:54:00+00
46188,NaN,Subscriber,NaN,1,1987.0,15929,404,382,456,46189,9 Ave & W 14 St,University Pl & E 14 St,-74.005509,40.740583,-73.992005,40.734927,2015-02-08 00:03:00+00,2015-02-07 23:55:00+00
46189,NaN,Subscriber,NaN,1,1983.0,17541,466,254,327,46190,W 25 St & 6 Ave,W 11 St & 6 Ave,-73.991449,40.743954,-73.998004,40.735324,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
46190,NaN,Subscriber,NaN,2,1983.0,14736,494,116,306,46191,W 26 St & 8 Ave,W 17 St & 8 Ave,-73.997236,40.747348,-74.001497,40.741776,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
46191,NaN,Subscriber,NaN,1,1984.0,16300,432,495,1248,46192,E 7 St & Avenue A,W 47 St & 10 Ave,-73.983799,40.726218,-73.993012,40.762699,2015-02-08 00:17:00+00,2015-02-07 23:56:00+00
46192,NaN,Subscriber,NaN,1,1959.0,16978,325,152,1165,46193,E 19 St & 3 Ave,Warren St & Church St,-73.984738,40.736245,-74.009106,40.714740,2015-02-08 00:15:00+00,2015-02-07 23:56:00+00
46193,NaN,Subscriber,NaN,1,1974.0,16722,295,461,993,46194,Pike St & E Broadway,E 20 St & 2 Ave,-73.992939,40.714067,-73.982050,40.735877,2015-02-08 00:13:00+00,2015-02-07 23:56:00+00
46194,NaN,Subscriber,NaN,2,1960.0,20184,265,455,1422,46195,Stanton St & Chrystie St,1 Ave & E 44 St,-73.991475,40.722293,-73.969053,40.750020,2015-02-08 00:20:00+00,2015-02-07 23:57:00+00
46195,NaN,Subscriber,NaN,1,1953.0,15585,325,470,689,46196,E 19 St & 3 Ave,W 20 St & 8 Ave,-73.984738,40.736245,-74.000040,40.743453,2015-02-08 00:08:00+00,2015-02-07 23:57:00+00
46196,NaN,Subscriber,NaN,2,1986.0,16395,325,474,428,46197,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:04:00+00,2015-02-07 23:57:00+00
46197,NaN,Subscriber,NaN,1,1986.0,15545,325,474,392,46198,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:03:00+00,2015-02-07 23:57:00+00
46198,NaN,Subscriber,NaN,2,1983.0,19540,334,368,548,46199,W 20 St & 7 Ave,Carmine St & 6 Ave,-73.997262,40.742388,-74.002150,40.730386,2015-02-08 00:08:00+00,2015-02-07 23:58:00+00
46199,NaN,Subscriber,NaN,2,1965.0,20998,417,439,917,46200,Barclay St & Church St,E 4 St & 2 Ave,-74.010202,40.712912,-73.989780,40.726281,2015-02-08 00:15:00+00,2015-02-07 23:59:00+00

# Task 1 — Familiarize with SQL Clauses

## Sort data by start_station_id, tripduration 
- Only checking trips with duration <= 3 hours

In [5]:
task1_1 = '''
SELECT * FROM citibike
WHERE tripduration <= 1080
ORDER by start_station_id, tripduration
'''

In [6]:
pd.read_csv(IO(queryCartoDB(task1_1)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,2,1980.0,19039,72,72,107,8998,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-03 10:12:00+00,2015-02-03 10:10:00+00
1,NaN,Subscriber,NaN,2,1959.0,18131,72,72,189,40759,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:43:00+00,2015-02-07 10:40:00+00
2,NaN,Subscriber,NaN,1,1995.0,19729,72,72,229,40757,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:44:00+00,2015-02-07 10:40:00+00
3,NaN,Subscriber,NaN,1,1970.0,16879,478,72,248,21948,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-05 06:24:00+00,2015-02-05 06:19:00+00
4,NaN,Subscriber,NaN,1,1983.0,15277,515,72,252,43099,W 43 St & 10 Ave,W 52 St & 11 Ave,-73.994618,40.760094,-73.993929,40.767272,2015-02-07 15:47:00+00,2015-02-07 15:43:00+00
5,NaN,Subscriber,NaN,1,1971.0,18492,478,72,261,32566,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-06 09:02:00+00,2015-02-06 08:58:00+00
6,NaN,Subscriber,NaN,1,1961.0,19216,478,72,276,15971,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-04 12:51:00+00,2015-02-04 12:46:00+00
7,NaN,Subscriber,NaN,1,1974.0,21588,447,72,283,41355,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-07 12:15:00+00,2015-02-07 12:10:00+00
8,NaN,Subscriber,NaN,1,1978.0,19124,514,72,288,42074,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-07 13:54:00+00,2015-02-07 13:50:00+00
9,NaN,Subscriber,NaN,1,1974.0,18174,447,72,301,2282,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-01 13:13:00+00,2015-02-01 13:08:00+00
10,NaN,Subscriber,NaN,1,1983.0,18198,526,72,304,44674,E 33 St & 5 Ave,W 52 St & 11 Ave,-73.984907,40.747659,-73.993929,40.767272,2015-02-07 18:36:00+00,2015-02-07 18:31:00+00
11,NaN,Subscriber,NaN,1,1982.0,19672,478,72,339,2142,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-01 13:00:00+00,2015-02-01 12:54:00+00
12,NaN,Subscriber,NaN,2,1986.0,14692,2021,72,344,649,W 45 St & 8 Ave,W 52 St & 11 Ave,-73.988597,40.759291,-73.993929,40.767272,2015-02-01 09:54:00+00,2015-02-01 09:49:00+00
13,NaN,Subscriber,NaN,1,1983.0,17669,447,72,345,44789,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-07 18:51:00+00,2015-02-07 18:46:00+00
14,NaN,Subscriber,NaN,1,1961.0,16754,478,72,348,9494,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-03 13:06:00+00,2015-02-03 13:01:00+00
15,NaN,Subscriber,NaN,1,1983.0,21114,500,72,359,42446,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-07 14:39:00+00,2015-02-07 14:33:00+00
16,NaN,Subscriber,NaN,1,1970.0,19729,515,72,366,41465,W 43 St & 10 Ave,W 52 St & 11 Ave,-73.994618,40.760094,-73.993929,40.767272,2015-02-07 12:36:00+00,2015-02-07 12:29:00+00
17,NaN,Subscriber,NaN,1,1981.0,18620,500,72,367,14395,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-04 09:05:00+00,2015-02-04 08:59:00+00
18,NaN,Subscriber,NaN,1,1981.0,20119,450,72,373,19984,W 49 St & 8 Ave,W 52 St & 11 Ave,-73.987882,40.762272,-73.993929,40.767272,2015-02-04 19:22:00+00,2015-02-04 19:16:00+00
19,NaN,Subscriber,NaN,1,1981.0,20988,500,72,375,8726,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-03 09:21:00+00,2015-02-03 09:15:00+00
20,NaN,Subscriber,NaN,2,1972.0,16310,500,72,377,25842,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 13:01:00+00,2015-02-05 12:55:00+00
21,NaN,Subscriber,NaN,1,1978.0,18287,514,72,377,26155,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-05 13:52:00+00,2015-02-05 13:46:00+00
22,NaN,Subscriber,NaN,1,1973.0,18991,500,72,379,25587,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 12:21:00+00,2015-02-05 12:15:00+00
23,NaN,Subscriber,NaN,1,1981.0,20600,500,72,380,24156,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 09:21:00+00,2015-02-05 09:14:00+00
24,NaN,Subscriber,NaN,1,1973.0,15927,479,72,386,27104,9 Ave & W 45 St,W 52 St & 11 Ave,-73.991255,40.760193,-73.993929,40.767272,2015-02-05 16:06:00+00,2015-02-05 16:00:00+00
25,NaN,Subscriber,NaN,1,1991.0,15282,514,72,387,3957,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-01 16:03:00+00,2015-02-01 15:57:00+00
26,NaN,Subscriber,NaN,1,1978.0,16405,529,72,388,31639,W 42 St & 8 Ave,W 52 St & 11 Ave,-73.990985,40.757570,-73.993929,40.767272,2015-02-06 08:00:00+00,2015-02-06 07:53:00+00
27,NaN,Subscriber,NaN,1,1980.0,17196,500,72,388,9194,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-03 11:30:00+00,2015-02-03 11:23:00+00
28,NaN,Subscriber,NaN,2,1986.0,17972,2021,72,396,33221,W 45 St & 8 Ave,W 52 St & 11 Ave,-73.988597,40.759291,-73.993929,40.767272,2015-02-06 10:06:00+00,2015-02-06 09:59:00+00
29,NaN,Subscriber,NaN,1,1974.0,19771,500,72,396,38564,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-06 20:01:00+00,2015-02-06 19:55:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40282,NaN,Subscriber,NaN,2,1980.0,16987,308,3002,683,1472,St James Pl & Oliver St,South End Ave & Liberty St,-73.998512,40.713079,-74.015756,40.711512,2015-02-01 11:55:00+00,2015-02-01 11:43:00+00
40283,NaN,Subscriber,NaN,1,1996.0,19309,358,3002,689,1863,Christopher St & Greenwich St,South End Ave & Liberty St,-74.007114,40.732916,-74.015756,40.711512,2015-02-01 12:36:00+00,2015-02-01 12:25:00+00
40284,NaN,Subscriber,NaN,1,1977.0,15189,151,3002,691,41246,Cleveland Pl & Spring St,South End Ave & Liberty St,-73.997203,40.721816,-74.015756,40.711512,2015-02-07 12:05:00+00,2015-02-07 11:53:00+00
40285,NaN,Subscriber,NaN,1,1944.0,15510,304,3002,700,8984,Broadway & Battery Pl,South End Ave & Liberty St,-74.013617,40.704633,-74.015756,40.711512,2015-02-03 10:20:00+00,2015-02-03 10:08:00+00
40286,NaN,Customer,NaN,0,NaN,17899,328,3002,705,3343,Watts St & Greenwich St,South End Ave & Liberty St,-74.009660,40.724055,-74.015756,40.711512,2015-02-01 15:08:00+00,2015-02-01 14:56:00+00
40287,NaN,Subscriber,NaN,1,1960.0,19303,377,3002,734,8909,6 Ave & Canal St,South End Ave & Liberty St,-74.005664,40.722438,-74.015756,40.711512,2015-02-03 10:00:00+00,2015-02-03 09:48:00+00
40288,NaN,Subscriber,NaN,1,1980.0,20901,369,3002,745,1628,Washington Pl & 6 Ave,South End Ave & Liberty St,-74.000264,40.732241,-74.015756,40.711512,2015-02-01 12:09:00+00,2015-02-01 11:57:00+00
40289,NaN,Subscriber,NaN,2,1967.0,18386,127,3002,751,2727,Barrow St & Hudson St,South End Ave & Liberty St,-74.006744,40.731724,-74.015756,40.711512,2015-02-01 14:08:00+00,2015-02-01 13:55:00+00
40290,NaN,Subscriber,NaN,1,1991.0,19783,329,3002,771,6876,Greenwich St & N Moore St,South End Ave & Liberty St,-74.010206,40.720434,-74.015756,40.711512,2015-02-02 10:29:00+00,2015-02-02 10:16:00+00
40291,NaN,Subscriber,NaN,1,1951.0,15977,348,3002,771,34225,W Broadway & Spring St,South End Ave & Liberty St,-74.001547,40.724910,-74.015756,40.711512,2015-02-06 13:16:00+00,2015-02-06 13:03:00+00
40292,NaN,Subscriber,NaN,2,1985.0,15977,316,3002,775,33170,Fulton St & William St,South End Ave & Liberty St,-74.006536,40.709560,-74.015756,40.711512,2015-02-06 10:06:00+00,2015-02-06 09:53:00+00
40293,NaN,Subscriber,NaN,1,1979.0,17004,368,3002,790,2205,Carmine St & 6 Ave,South End Ave & Liberty St,-74.002150,40.730386,-74.015756,40.711512,2015-02-01 13:14:00+00,2015-02-01 13:01:00+00
40294,NaN,Subscriber,NaN,1,1959.0,19434,355,3002,834,42784,Bayard St & Baxter St,South End Ave & Liberty St,-73.999744,40.716021,-74.015756,40.711512,2015-02-07 15:25:00+00,2015-02-07 15:11:00+00
40295,NaN,Subscriber,NaN,1,1972.0,20637,327,3002,838,5261,Vesey Pl & River Terrace,South End Ave & Liberty St,-74.016584,40.715338,-74.015756,40.711512,2015-02-01 18:20:00+00,2015-02-01 18:06:00+00
40296,NaN,Subscriber,NaN,1,1956.0,17180,358,3002,841,16654,Christopher St & Greenwich St,South End Ave & Liberty St,-74.007114,40.732916,-74.015756,40.711512,2015-02-04 14:46:00+00,2015-02-04 14:32:00+00
40297,NaN,Subscriber,NaN,1,1977.0,21407,151,3002,850,37727,Cleveland Pl & Spring St,South End Ave & Liberty St,-73.997203,40.721816,-74.015756,40.711512,2015-02-06 18:48:00+00,2015-02-06 18:34:00+00
40298,NaN,Subscriber,NaN,1,1959.0,15748,355,3002,858,1587,Bayard St & Baxter St,South End Ave & Liberty St,-73.999744,40.716021,-74.015756,40.711512,2015-02-01 12:07:00+00,2015-02-01 11:53:00+00
40299,NaN,Subscriber,NaN,2,1980.0,14558,3002,3002,876,29964,South End Ave & Liberty St,South End Ave & Liberty St,-74.015756,40.711512,-74.015756,40.711512,2015-02-05 20:06:00+00,2015-02-05 19:51:00+00
40300,NaN,Subscriber,NaN,1,1974.0,19000,380,3002,876,43446,W 4 St & 7 Ave S,South End Ave & Liberty St,-74.002939,40.734011,-74.015756,40.711512,2015-02-07 16:35:00+00,2015-02-07 16:20:00+00
40301,NaN,Subscriber,NaN,1,1955.0,17586,355,3002,879,43112,Bayard St & Baxter St,South End Ave & Liberty St,-73.999744,40.716021,-74.015756,40.711512,2015-02-07 16:00:00+00,2015-02-07 15:45:00+00
40302,NaN,Subscriber,NaN,1,1988.0,15904,2000,3002,925,15488,Front St & Washington St,South End Ave & Liberty St,-73.989402,40.702551,-74.015756,40.711512,2015-02-04 11:40:00+00,2015-02-04 11:25:00+00
40303,NaN,Subscriber,NaN,2,1973.0,16144,401,3002,931,12373,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-03 21:51:00+00,2015-02-03 21:35:00+00
40304,NaN,Subscriber,NaN,2,1980.0,20156,263,3002,938,36626,Elizabeth St & Hester St,South End Ave & Liberty St,-73.996375,40.717290,-74.015756,40.711512,2015-02-06 17:40:00+00,2015-02-06 17:25:00+00
40305,NaN,Subscriber,NaN,2,1964.0,20744,531,3002,943,4413,Forsyth St & Broome St,South End Ave & Liberty St,-73.992663,40.718939,-74.015756,40.711512,2015-02-01 17:00:00+00,2015-02-01 16:45:00+00
40306,NaN,Subscriber,NaN,1,1983.0,20379,496,3002,951,40770,E 16 St & 5 Ave,South End Ave & Liberty St,-73.992390,40.737262,-74.015756,40.711512,2015-02-07 10:58:00+00,2015-02-07 10:42:00+00
40307,NaN,Customer,NaN,0,NaN,16565,128,3002,1005,44156,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-07 17:45:00+00,2015-02-07 17:29:00+00
40308,NaN,Subscriber,NaN,1,1997.0,17310,128,3002,1031,38837,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-06 20:57:00+00,2015-02-06 20:40:00+00
40309,NaN,Subscriber,NaN,2,1973.0,14906,401,3002,1032,20648,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-04 20:41:00+00,2015-02-04 20:24:00+00
40310,NaN,Subscriber,NaN,1,1998.0,15090,128,3002,1045,38836,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-06 20:57:00+00,2015-02-06 20:40:00+00
40311,NaN,Subscriber,NaN,2,1973.0,18797,401,3002,1058,28070,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-05 17:42:00+00,2015-02-05 17:24:00+00

## Only show the top/last 10 records (aka head and tail in SQL)

In [7]:
task1_2 = '''
SELECT * FROM citibike
WHERE tripduration <= 1080
ORDER by start_station_id, tripduration
LIMIT 10
'''
pd.read_csv(IO(queryCartoDB(task1_2)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,2,1980,19039,72,72,107,8998,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-03 10:12:00+00,2015-02-03 10:10:00+00
1,NaN,Subscriber,NaN,2,1959,18131,72,72,189,40759,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:43:00+00,2015-02-07 10:40:00+00
2,NaN,Subscriber,NaN,1,1995,19729,72,72,229,40757,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:44:00+00,2015-02-07 10:40:00+00
3,NaN,Subscriber,NaN,1,1970,16879,478,72,248,21948,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-05 06:24:00+00,2015-02-05 06:19:00+00
4,NaN,Subscriber,NaN,1,1983,15277,515,72,252,43099,W 43 St & 10 Ave,W 52 St & 11 Ave,-73.994618,40.760094,-73.993929,40.767272,2015-02-07 15:47:00+00,2015-02-07 15:43:00+00
5,NaN,Subscriber,NaN,1,1971,18492,478,72,261,32566,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-06 09:02:00+00,2015-02-06 08:58:00+00
6,NaN,Subscriber,NaN,1,1961,19216,478,72,276,15971,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-04 12:51:00+00,2015-02-04 12:46:00+00
7,NaN,Subscriber,NaN,1,1974,21588,447,72,283,41355,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-07 12:15:00+00,2015-02-07 12:10:00+00
8,NaN,Subscriber,NaN,1,1978,19124,514,72,288,42074,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-07 13:54:00+00,2015-02-07 13:50:00+00
9,NaN,Subscriber,NaN,1,1974,18174,447,72,301,2282,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-01 13:13:00+00,2015-02-01 13:08:00+00

In [8]:
task1_3 = '''
SELECT * FROM citibike
WHERE tripduration <= 1080
ORDER by start_station_id DESC, tripduration DESC
LIMIT 10
'''
pd.read_csv(IO(queryCartoDB(task1_3)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,2,1973.0,18797,401,3002,1058,28070,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-05 17:42:00+00,2015-02-05 17:24:00+00
1,NaN,Subscriber,NaN,1,1998.0,15090,128,3002,1045,38836,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-06 20:57:00+00,2015-02-06 20:40:00+00
2,NaN,Subscriber,NaN,2,1973.0,14906,401,3002,1032,20648,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-04 20:41:00+00,2015-02-04 20:24:00+00
3,NaN,Subscriber,NaN,1,1997.0,17310,128,3002,1031,38837,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-06 20:57:00+00,2015-02-06 20:40:00+00
4,NaN,Customer,NaN,0,NaN,16565,128,3002,1005,44156,MacDougal St & Prince St,South End Ave & Liberty St,-74.002971,40.727103,-74.015756,40.711512,2015-02-07 17:45:00+00,2015-02-07 17:29:00+00
5,NaN,Subscriber,NaN,1,1983.0,20379,496,3002,951,40770,E 16 St & 5 Ave,South End Ave & Liberty St,-73.992390,40.737262,-74.015756,40.711512,2015-02-07 10:58:00+00,2015-02-07 10:42:00+00
6,NaN,Subscriber,NaN,2,1964.0,20744,531,3002,943,4413,Forsyth St & Broome St,South End Ave & Liberty St,-73.992663,40.718939,-74.015756,40.711512,2015-02-01 17:00:00+00,2015-02-01 16:45:00+00
7,NaN,Subscriber,NaN,2,1980.0,20156,263,3002,938,36626,Elizabeth St & Hester St,South End Ave & Liberty St,-73.996375,40.717290,-74.015756,40.711512,2015-02-06 17:40:00+00,2015-02-06 17:25:00+00
8,NaN,Subscriber,NaN,2,1973.0,16144,401,3002,931,12373,Allen St & Rivington St,South End Ave & Liberty St,-73.989978,40.720196,-74.015756,40.711512,2015-02-03 21:51:00+00,2015-02-03 21:35:00+00
9,NaN,Subscriber,NaN,1,1988.0,15904,2000,3002,925,15488,Front St & Washington St,South End Ave & Liberty St,-73.989402,40.702551,-74.015756,40.711512,2015-02-04 11:40:00+00,2015-02-04 11:25:00+00

## List all unique start_station_id values

In [9]:
task1_4 = '''
SELECT DISTINCT start_station_id FROM citibike
ORDER BY start_station_id
'''
pd.read_csv(IO(queryCartoDB(task1_4)), sep=',')

     start_station_id  Unnamed: 1
0                  72         NaN
1                  79         NaN
2                  82         NaN
3                  83         NaN
4                 116         NaN
5                 119         NaN
6                 120         NaN
7                 127         NaN
8                 128         NaN
9                 137         NaN
10                143         NaN
11                144         NaN
12                146         NaN
13                147         NaN
14                150         NaN
15                151         NaN
16                152         NaN
17                153         NaN
18                157         NaN
19                160         NaN
20                161         NaN
21                164         NaN
22                167         NaN
23                168         NaN
24                173         NaN
25                174         NaN
26                195         NaN
27                212         NaN
28                216         NaN
29                217         NaN
..                ...         ...
297               525         NaN
298               526         NaN
299               527         NaN
300               528         NaN
301               529         NaN
302               530         NaN
303               531         NaN
304               532         NaN
305               533         NaN
306               534         NaN
307               537         NaN
308               538         NaN
309               539         NaN
310               545         NaN
311               546         NaN
312              2000         NaN
313              2001         NaN
314              2002         NaN
315              2004         NaN
316              2005         NaN
317              2006         NaN
318              2008         NaN
319              2009         NaN
320              2010         NaN
321              2012         NaN
322              2017         NaN
323              2021         NaN
324              2022         NaN
325              2023         NaN
326              3002         NaN

[327 rows x 2 columns]

## Aggregation functions: 
- Count the number of trips (aka wc -l in SQL) 
-  Find the average/min/max trip duration

In [10]:
task1_5 = '''
SELECT COUNT(cartodb_id) FROM citibike
'''
pd.read_csv(IO(queryCartoDB(task1_5)), sep=',')

   count  Unnamed: 1
0  46200         NaN

In [11]:
task1_6 = '''
SELECT AVG(tripduration),MIN(tripduration),MAX(tripduration) FROM citibike
'''
pd.read_csv(IO(queryCartoDB(task1_6)), sep=',')

          avg  min    max
0  675.865823   60  43016

# Task 2 — Working with date/time

## Selecting trips started on Feb-02-2015 only

In [12]:
task2_1 = '''
SELECT * FROM citibike
WHERE starttime <= '2015-02-02 23:59:59' AND starttime > '2015-02-01 23:59:59'
'''
pd.read_csv(IO(queryCartoDB(task2_1)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,1,1992.0,20684,489,442,199,6442,10 Ave & W 28 St,W 27 St & 7 Ave,-74.001768,40.750664,-73.993915,40.746647,2015-02-02 00:05:00+00,2015-02-02 00:02:00+00
1,NaN,Subscriber,NaN,2,1964.0,16094,349,326,418,6443,Rivington St & Ridge St,E 11 St & 1 Ave,-73.983299,40.718502,-73.984267,40.729538,2015-02-02 00:10:00+00,2015-02-02 00:03:00+00
2,NaN,Subscriber,NaN,1,1974.0,17362,415,279,276,6444,Pearl St & Hanover Square,Peck Slip & Front St,-74.009260,40.704718,-74.001670,40.707873,2015-02-02 00:09:00+00,2015-02-02 00:04:00+00
3,NaN,Subscriber,NaN,2,1992.0,15475,237,496,420,6445,E 11 St & 2 Ave,E 16 St & 5 Ave,-73.986724,40.730473,-73.992390,40.737262,2015-02-02 00:13:00+00,2015-02-02 00:06:00+00
4,NaN,Subscriber,NaN,1,1968.0,16272,450,477,304,6446,W 49 St & 8 Ave,W 41 St & 8 Ave,-73.987882,40.762272,-73.990026,40.756405,2015-02-02 00:12:00+00,2015-02-02 00:07:00+00
5,NaN,Subscriber,NaN,1,1979.0,16370,391,467,622,6447,Clark St & Henry St,Dean St & 4 Ave,-73.993446,40.697601,-73.978951,40.683125,2015-02-02 00:18:00+00,2015-02-02 00:08:00+00
6,NaN,Subscriber,NaN,1,1963.0,19437,482,434,371,6448,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 00:15:00+00,2015-02-02 00:09:00+00
7,NaN,Subscriber,NaN,1,1982.0,21211,2008,330,477,6449,Little West St & 1 Pl,Reade St & Broadway,-74.016777,40.705693,-74.005628,40.714505,2015-02-02 00:19:00+00,2015-02-02 00:11:00+00
8,NaN,Subscriber,NaN,2,1978.0,21417,423,521,743,6450,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-02 00:25:00+00,2015-02-02 00:12:00+00
9,NaN,Subscriber,NaN,1,1956.0,15722,453,504,599,6451,W 22 St & 8 Ave,1 Ave & E 15 St,-73.999154,40.744751,-73.981656,40.732219,2015-02-02 00:22:00+00,2015-02-02 00:12:00+00
10,NaN,Subscriber,NaN,1,1962.0,18972,236,285,345,6452,St Marks Pl & 2 Ave,Broadway & E 14 St,-73.987140,40.728419,-73.990741,40.734546,2015-02-02 00:18:00+00,2015-02-02 00:12:00+00
11,NaN,Subscriber,NaN,1,1980.0,19628,476,301,721,6453,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-02 00:25:00+00,2015-02-02 00:13:00+00
12,NaN,Subscriber,NaN,1,1978.0,15169,376,279,182,6454,John St & William St,Peck Slip & Front St,-74.007222,40.708621,-74.001670,40.707873,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
13,NaN,Subscriber,NaN,1,1997.0,17533,411,342,154,6455,E 6 St & Avenue D,Columbia St & Rivington St,-73.976687,40.722281,-73.980166,40.717400,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
14,NaN,Subscriber,NaN,1,1983.0,19761,491,470,435,6456,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-02 00:21:00+00,2015-02-02 00:14:00+00
15,NaN,Subscriber,NaN,1,1993.0,17267,393,236,310,6457,E 5 St & Avenue C,St Marks Pl & 2 Ave,-73.979955,40.722992,-73.987140,40.728419,2015-02-02 00:20:00+00,2015-02-02 00:15:00+00
16,NaN,Subscriber,NaN,1,1964.0,18691,470,470,1274,6458,W 20 St & 8 Ave,W 20 St & 8 Ave,-74.000040,40.743453,-74.000040,40.743453,2015-02-02 00:37:00+00,2015-02-02 00:16:00+00
17,NaN,Subscriber,NaN,1,1977.0,17106,174,485,642,6459,E 25 St & 1 Ave,W 37 St & 5 Ave,-73.977387,40.738177,-73.983390,40.750380,2015-02-02 00:29:00+00,2015-02-02 00:18:00+00
18,NaN,Subscriber,NaN,1,1973.0,20009,483,345,256,6460,E 12 St & 3 Ave,W 13 St & 6 Ave,-73.988900,40.732233,-73.997044,40.736494,2015-02-02 00:22:00+00,2015-02-02 00:18:00+00
19,NaN,Subscriber,NaN,1,1979.0,18777,442,489,334,6461,W 27 St & 7 Ave,10 Ave & W 28 St,-73.993915,40.746647,-74.001768,40.750664,2015-02-02 00:25:00+00,2015-02-02 00:19:00+00
20,NaN,Subscriber,NaN,1,1989.0,15357,174,507,90,6462,E 25 St & 1 Ave,E 25 St & 2 Ave,-73.977387,40.738177,-73.979738,40.739126,2015-02-02 00:20:00+00,2015-02-02 00:19:00+00
21,NaN,Subscriber,NaN,1,1983.0,18487,405,380,203,6463,Washington St & Gansevoort St,W 4 St & 7 Ave S,-74.008119,40.739323,-74.002939,40.734011,2015-02-02 00:23:00+00,2015-02-02 00:20:00+00
22,NaN,Subscriber,NaN,1,1981.0,20863,439,334,649,6464,E 4 St & 2 Ave,W 20 St & 7 Ave,-73.989780,40.726281,-73.997262,40.742388,2015-02-02 00:32:00+00,2015-02-02 00:22:00+00
23,NaN,Subscriber,NaN,1,1970.0,16539,448,508,319,6465,W 37 St & 10 Ave,W 46 St & 11 Ave,-73.997901,40.756604,-73.996674,40.763414,2015-02-02 00:29:00+00,2015-02-02 00:23:00+00
24,NaN,Subscriber,NaN,1,1961.0,18737,301,428,154,6466,E 2 St & Avenue B,E 3 St & 1 Ave,-73.983688,40.722174,-73.987834,40.724677,2015-02-02 00:30:00+00,2015-02-02 00:27:00+00
25,NaN,Subscriber,NaN,2,1980.0,17797,195,331,550,6467,Liberty St & Broadway,Pike St & Monroe St,-74.010434,40.709056,-73.991930,40.711731,2015-02-02 00:37:00+00,2015-02-02 00:28:00+00
26,NaN,Subscriber,NaN,1,1990.0,20638,478,529,268,6468,11 Ave & W 41 St,W 42 St & 8 Ave,-73.998842,40.760301,-73.990985,40.757570,2015-02-02 00:34:00+00,2015-02-02 00:29:00+00
27,NaN,Subscriber,NaN,1,1989.0,17636,366,421,153,6469,Clinton Ave & Myrtle Ave,Clermont Ave & Park Ave,-73.968896,40.693261,-73.971297,40.695734,2015-02-02 00:31:00+00,2015-02-02 00:29:00+00
28,NaN,Subscriber,NaN,1,1982.0,18472,494,284,309,6470,W 26 St & 8 Ave,Greenwich Ave & 8 Ave,-73.997236,40.747348,-74.002638,40.739017,2015-02-02 00:36:00+00,2015-02-02 00:31:00+00
29,NaN,Subscriber,NaN,1,1968.0,17456,252,383,138,6471,MacDougal St & Washington Sq,Greenwich Ave & Charles St,-73.998522,40.732264,-74.000271,40.735238,2015-02-02 00:35:00+00,2015-02-02 00:33:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,NaN,Subscriber,NaN,1,1985.0,20572,380,312,722,7871,W 4 St & 7 Ave S,Allen St & E Houston St,-74.002939,40.734011,-73.989111,40.722055,2015-02-02 23:20:00+00,2015-02-02 23:08:00+00
1430,NaN,Subscriber,NaN,1,1981.0,20338,491,486,274,7872,E 24 St & Park Ave S,Broadway & W 29 St,-73.986022,40.740964,-73.988557,40.746201,2015-02-02 23:12:00+00,2015-02-02 23:08:00+00
1431,NaN,Subscriber,NaN,1,1978.0,15826,515,352,951,7873,W 43 St & 10 Ave,W 56 St & 6 Ave,-73.994618,40.760094,-73.977225,40.763406,2015-02-02 23:27:00+00,2015-02-02 23:11:00+00
1432,NaN,Subscriber,NaN,1,1990.0,18325,521,489,276,7874,8 Ave & W 31 St,10 Ave & W 28 St,-73.994811,40.750450,-74.001768,40.750664,2015-02-02 23:20:00+00,2015-02-02 23:16:00+00
1433,NaN,Subscriber,NaN,1,1977.0,16654,434,494,426,7875,9 Ave & W 18 St,W 26 St & 8 Ave,-74.003664,40.743174,-73.997236,40.747348,2015-02-02 23:24:00+00,2015-02-02 23:17:00+00
1434,NaN,Subscriber,NaN,1,1966.0,20902,229,402,578,7876,Great Jones St,Broadway & E 22 St,-73.993790,40.727434,-73.989551,40.740343,2015-02-02 23:28:00+00,2015-02-02 23:19:00+00
1435,NaN,Subscriber,NaN,1,1954.0,20796,2017,164,2621,7877,E 43 St & 2 Ave,E 47 St & 2 Ave,-73.971214,40.750224,-73.970325,40.753231,2015-02-03 00:06:00+00,2015-02-02 23:22:00+00
1436,NaN,Subscriber,NaN,1,1989.0,20160,449,498,621,7878,W 52 St & 9 Ave,Broadway & W 32 St,-73.987895,40.764618,-73.988084,40.748549,2015-02-02 23:32:00+00,2015-02-02 23:22:00+00
1437,NaN,Subscriber,NaN,1,1974.0,17392,477,521,323,7879,W 41 St & 8 Ave,8 Ave & W 31 St,-73.990026,40.756405,-73.994811,40.750450,2015-02-02 23:29:00+00,2015-02-02 23:23:00+00
1438,NaN,Subscriber,NaN,1,1963.0,17263,482,434,393,7880,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 23:31:00+00,2015-02-02 23:24:00+00
1439,NaN,Subscriber,NaN,1,1955.0,19858,497,161,597,7881,E 17 St & Broadway,LaGuardia Pl & W 3 St,-73.990093,40.737050,-73.998102,40.729170,2015-02-02 23:35:00+00,2015-02-02 23:25:00+00
1440,NaN,Subscriber,NaN,1,1979.0,20319,462,494,244,7882,W 22 St & 10 Ave,W 26 St & 8 Ave,-74.004519,40.746920,-73.997236,40.747348,2015-02-02 23:30:00+00,2015-02-02 23:25:00+00
1441,NaN,Subscriber,NaN,1,1977.0,21600,127,306,1023,7883,Barrow St & Hudson St,Cliff St & Fulton St,-74.006744,40.731724,-74.005301,40.708235,2015-02-02 23:43:00+00,2015-02-02 23:26:00+00
1442,NaN,Subscriber,NaN,1,1986.0,18791,473,349,419,7884,Rivington St & Chrystie St,Rivington St & Ridge St,-73.991925,40.721101,-73.983299,40.718502,2015-02-02 23:38:00+00,2015-02-02 23:31:00+00
1443,NaN,Subscriber,NaN,1,1966.0,17730,358,450,1429,7885,Christopher St & Greenwich St,W 49 St & 8 Ave,-74.007114,40.732916,-73.987882,40.762272,2015-02-02 23:55:00+00,2015-02-02 23:32:00+00
1444,NaN,Subscriber,NaN,1,1980.0,18147,477,519,676,7886,W 41 St & 8 Ave,Pershing Square North,-73.990026,40.756405,-73.977706,40.751873,2015-02-02 23:44:00+00,2015-02-02 23:32:00+00
1445,NaN,Subscriber,NaN,1,1959.0,20249,489,546,879,7887,10 Ave & W 28 St,E 30 St & Park Ave S,-74.001768,40.750664,-73.983035,40.744449,2015-02-02 23:48:00+00,2015-02-02 23:33:00+00
1446,NaN,Subscriber,NaN,1,1988.0,18078,432,336,593,7888,E 7 St & Avenue A,Sullivan St & Washington Sq,-73.983799,40.726218,-73.999061,40.730477,2015-02-02 23:45:00+00,2015-02-02 23:35:00+00
1447,NaN,Subscriber,NaN,1,1983.0,16808,164,529,839,7889,E 47 St & 2 Ave,W 42 St & 8 Ave,-73.970325,40.753231,-73.990985,40.757570,2015-02-02 23:50:00+00,2015-02-02 23:36:00+00
1448,NaN,Subscriber,NaN,1,1986.0,21355,368,402,560,7890,Carmine St & 6 Ave,Broadway & E 22 St,-74.002150,40.730386,-73.989551,40.740343,2015-02-02 23:46:00+00,2015-02-02 23:37:00+00
1449,NaN,Subscriber,NaN,1,1994.0,15359,511,504,165,7891,E 14 St & Avenue B,1 Ave & E 15 St,-73.977724,40.729387,-73.981656,40.732219,2015-02-02 23:40:00+00,2015-02-02 23:37:00+00
1450,NaN,Subscriber,NaN,2,1982.0,18250,489,505,813,7892,10 Ave & W 28 St,6 Ave & W 33 St,-74.001768,40.750664,-73.988484,40.749013,2015-02-02 23:56:00+00,2015-02-02 23:42:00+00
1451,NaN,Subscriber,NaN,1,1987.0,16969,507,509,764,7893,E 25 St & 2 Ave,9 Ave & W 22 St,-73.979738,40.739126,-74.001971,40.745497,2015-02-02 23:55:00+00,2015-02-02 23:42:00+00
1452,NaN,Subscriber,NaN,1,1979.0,18825,397,496,2111,7894,Fulton St & Clermont Ave,E 16 St & 5 Ave,-73.969223,40.684157,-73.992390,40.737262,2015-02-03 00:18:00+00,2015-02-02 23:43:00+00
1453,NaN,Subscriber,NaN,1,1983.0,19000,439,280,518,7895,E 4 St & 2 Ave,E 10 St & 5 Ave,-73.989780,40.726281,-73.995101,40.733320,2015-02-02 23:52:00+00,2015-02-02 23:43:00+00
1454,NaN,Subscriber,NaN,1,1977.0,20723,440,484,371,7896,E 45 St & 3 Ave,W 44 St & 5 Ave,-73.972826,40.752554,-73.980144,40.755003,2015-02-02 23:52:00+00,2015-02-02 23:45:00+00
1455,NaN,Subscriber,NaN,1,1988.0,16528,417,224,188,7897,Barclay St & Church St,Spruce St & Nassau St,-74.010202,40.712912,-74.005524,40.711464,2015-02-02 23:50:00+00,2015-02-02 23:47:00+00
1456,NaN,Subscriber,NaN,1,1988.0,16541,394,345,689,7898,E 9 St & Avenue C,W 13 St & 6 Ave,-73.977688,40.725213,-73.997044,40.736494,2015-02-03 00:02:00+00,2015-02-02 23:50:00+00
1457,NaN,Subscriber,NaN,1,1961.0,14878,537,453,634,7899,Lexington Ave & E 24 St,W 22 St & 8 Ave,-73.984092,40.740259,-73.999154,40.744751,2015-02-03 00:05:00+00,2015-02-02 23:55:00+00
1458,NaN,Subscriber,NaN,2,1976.0,16326,302,285,733,7900,Avenue D & E 3 St,Broadway & E 14 St,-73.977932,40.720828,-73.990741,40.734546,2015-02-03 00:10:00+00,2015-02-02 23:58:00+00

## Selecting trips started on the weekends
- What are average trip duration during weekends?

In [13]:
task2_2 = '''
SELECT * FROM citibike
WHERE extract(DOW FROM starttime) in (0,6) 
'''
pd.read_csv(IO(queryCartoDB(task2_2)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,1,1965.0,19217,462,435,351,5960,W 22 St & 10 Ave,W 21 St & 6 Ave,-74.004519,40.746920,-73.994156,40.741740,2015-02-01 20:42:00+00,2015-02-01 20:36:00+00
1,NaN,Subscriber,NaN,2,1978.0,17131,423,521,801,1,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-01 00:14:00+00,2015-02-01 00:00:00+00
2,NaN,Subscriber,NaN,1,1993.0,21289,504,497,379,2,1 Ave & E 15 St,E 17 St & Broadway,-73.981656,40.732219,-73.990093,40.737050,2015-02-01 00:07:00+00,2015-02-01 00:00:00+00
3,NaN,Subscriber,NaN,2,1969.0,18903,127,281,2474,3,Barrow St & Hudson St,Grand Army Plaza & Central Park S,-74.006744,40.731724,-73.973715,40.764397,2015-02-01 00:42:00+00,2015-02-01 00:01:00+00
4,NaN,Subscriber,NaN,2,1985.0,21044,505,2004,818,4,6 Ave & W 33 St,6 Ave & Broome St,-73.988484,40.749013,-74.004704,40.724399,2015-02-01 00:15:00+00,2015-02-01 00:01:00+00
5,NaN,Subscriber,NaN,1,1957.0,19868,83,323,544,5,Atlantic Ave & Fort Greene Pl,Lawrence St & Willoughby St,-73.976323,40.683826,-73.986317,40.692362,2015-02-01 00:10:00+00,2015-02-01 00:01:00+00
6,NaN,Subscriber,NaN,1,1979.0,15854,2002,373,717,6,Wythe Ave & Metropolitan Ave,Willoughby Ave & Walworth St,-73.963198,40.716887,-73.953820,40.693317,2015-02-01 00:14:00+00,2015-02-01 00:02:00+00
7,NaN,Subscriber,NaN,1,1983.0,15173,504,352,1306,7,1 Ave & E 15 St,W 56 St & 6 Ave,-73.981656,40.732219,-73.977225,40.763406,2015-02-01 00:26:00+00,2015-02-01 00:04:00+00
8,NaN,Subscriber,NaN,1,1955.0,17862,116,439,913,8,W 17 St & 8 Ave,E 4 St & 2 Ave,-74.001497,40.741776,-73.989780,40.726281,2015-02-01 00:19:00+00,2015-02-01 00:04:00+00
9,NaN,Subscriber,NaN,2,1985.0,21183,2012,335,759,9,E 27 St & 1 Ave,Washington Pl & Broadway,-73.976806,40.739445,-73.994046,40.729039,2015-02-01 00:17:00+00,2015-02-01 00:04:00+00
10,NaN,Subscriber,NaN,1,1982.0,14843,444,284,585,10,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
11,NaN,Subscriber,NaN,2,1988.0,16936,444,284,581,11,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
12,NaN,Subscriber,NaN,2,1991.0,21507,472,498,204,12,E 32 St & Park Ave,Broadway & W 32 St,-73.981948,40.745712,-73.988084,40.748549,2015-02-01 00:08:00+00,2015-02-01 00:05:00+00
13,NaN,Subscriber,NaN,2,1982.0,17456,307,368,1169,13,Canal St & Rutgers St,Carmine St & 6 Ave,-73.989900,40.714275,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:07:00+00
14,NaN,Subscriber,NaN,2,1990.0,14679,2012,326,419,14,E 27 St & 1 Ave,E 11 St & 1 Ave,-73.976806,40.739445,-73.984267,40.729538,2015-02-01 00:14:00+00,2015-02-01 00:07:00+00
15,NaN,Subscriber,NaN,1,1977.0,18978,212,285,527,15,W 16 St & The High Line,Broadway & E 14 St,-74.006818,40.743349,-73.990741,40.734546,2015-02-01 00:17:00+00,2015-02-01 00:09:00+00
16,NaN,Subscriber,NaN,1,1968.0,16496,488,368,1013,16,W 39 St & 9 Ave,Carmine St & 6 Ave,-73.993722,40.756458,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:10:00+00
17,NaN,Subscriber,NaN,1,1990.0,17107,331,394,587,17,Pike St & Monroe St,E 9 St & Avenue C,-73.991930,40.711731,-73.977688,40.725213,2015-02-01 00:23:00+00,2015-02-01 00:13:00+00
18,NaN,Subscriber,NaN,1,1987.0,16984,507,326,525,18,E 25 St & 2 Ave,E 11 St & 1 Ave,-73.979738,40.739126,-73.984267,40.729538,2015-02-01 00:22:00+00,2015-02-01 00:13:00+00
19,NaN,Subscriber,NaN,1,1980.0,15997,305,493,670,19,E 58 St & 3 Ave,W 45 St & 6 Ave,-73.967245,40.760958,-73.982912,40.756800,2015-02-01 00:26:00+00,2015-02-01 00:14:00+00
20,NaN,Subscriber,NaN,1,1960.0,21516,223,445,711,20,W 13 St & 7 Ave,E 10 St & Avenue A,-73.999947,40.737815,-73.981420,40.727408,2015-02-01 00:27:00+00,2015-02-01 00:15:00+00
21,NaN,Subscriber,NaN,1,1986.0,15815,457,428,1559,21,Broadway & W 58 St,E 3 St & 1 Ave,-73.981693,40.766953,-73.987834,40.724677,2015-02-01 00:42:00+00,2015-02-01 00:16:00+00
22,NaN,Subscriber,NaN,1,1987.0,18727,477,228,683,22,W 41 St & 8 Ave,E 48 St & 3 Ave,-73.990026,40.756405,-73.971879,40.754601,2015-02-01 00:27:00+00,2015-02-01 00:16:00+00
23,NaN,Subscriber,NaN,1,1969.0,14982,488,513,522,23,W 39 St & 9 Ave,W 56 St & 10 Ave,-73.993722,40.756458,-73.988639,40.768254,2015-02-01 00:24:00+00,2015-02-01 00:16:00+00
24,NaN,Subscriber,NaN,1,1957.0,16391,518,507,389,24,E 39 St & 2 Ave,E 25 St & 2 Ave,-73.973442,40.747804,-73.979738,40.739126,2015-02-01 00:23:00+00,2015-02-01 00:16:00+00
25,NaN,Subscriber,NaN,1,1981.0,15947,473,439,276,25,Rivington St & Chrystie St,E 4 St & 2 Ave,-73.991925,40.721101,-73.989780,40.726281,2015-02-01 00:21:00+00,2015-02-01 00:16:00+00
26,NaN,Subscriber,NaN,1,1993.0,16917,531,128,907,26,Forsyth St & Broome St,MacDougal St & Prince St,-73.992663,40.718939,-74.002971,40.727103,2015-02-01 00:32:00+00,2015-02-01 00:17:00+00
27,NaN,Subscriber,NaN,1,1975.0,15924,528,490,946,27,2 Ave & E 31 St,8 Ave & W 33 St,-73.977061,40.742909,-73.993934,40.751551,2015-02-01 00:33:00+00,2015-02-01 00:18:00+00
28,NaN,Subscriber,NaN,1,1973.0,21321,502,350,144,28,Henry St & Grand St,Clinton St & Grand St,-73.981346,40.714215,-73.987030,40.715595,2015-02-01 00:21:00+00,2015-02-01 00:18:00+00
29,NaN,Subscriber,NaN,2,1973.0,16861,401,250,257,29,Allen St & Rivington St,Lafayette St & Jersey St,-73.989978,40.720196,-73.995653,40.724561,2015-02-01 00:23:00+00,2015-02-01 00:19:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13201,NaN,Subscriber,NaN,1,1988.0,15733,435,335,812,46171,W 21 St & 6 Ave,Washington Pl & Broadway,-73.994156,40.741740,-73.994046,40.729039,2015-02-08 00:05:00+00,2015-02-07 23:51:00+00
13202,NaN,Subscriber,NaN,1,1995.0,16931,504,361,647,46172,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:51:00+00
13203,NaN,Subscriber,NaN,1,1987.0,17202,401,152,563,46173,Allen St & Rivington St,Warren St & Church St,-73.989978,40.720196,-74.009106,40.714740,2015-02-08 00:00:00+00,2015-02-07 23:51:00+00
13204,NaN,Subscriber,NaN,2,1989.0,20314,439,483,470,46174,E 4 St & 2 Ave,E 12 St & 3 Ave,-73.989780,40.726281,-73.988900,40.732233,2015-02-07 23:59:00+00,2015-02-07 23:51:00+00
13205,NaN,Subscriber,NaN,1,1989.0,21531,395,467,299,46175,Bond St & Schermerhorn St,Dean St & 4 Ave,-73.984106,40.688070,-73.978951,40.683125,2015-02-07 23:56:00+00,2015-02-07 23:51:00+00
13206,NaN,Subscriber,NaN,1,1968.0,21491,504,361,629,46176,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:52:00+00
13207,NaN,Subscriber,NaN,1,1990.0,15367,380,402,499,46177,W 4 St & 7 Ave S,Broadway & E 22 St,-74.002939,40.734011,-73.989551,40.740343,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
13208,NaN,Subscriber,NaN,2,1973.0,18978,368,369,474,46178,Carmine St & 6 Ave,Washington Pl & 6 Ave,-74.002150,40.730386,-74.000264,40.732241,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
13209,NaN,Subscriber,NaN,1,1980.0,19507,504,476,345,46179,1 Ave & E 15 St,E 31 St & 3 Ave,-73.981656,40.732219,-73.979661,40.743943,2015-02-07 23:58:00+00,2015-02-07 23:52:00+00
13210,NaN,Subscriber,NaN,1,1980.0,16936,160,499,829,46180,E 37 St & Lexington Ave,Broadway & W 60 St,-73.978311,40.748238,-73.981918,40.769155,2015-02-08 00:07:00+00,2015-02-07 23:53:00+00
13211,NaN,Subscriber,NaN,1,1982.0,18689,531,368,776,46181,Forsyth St & Broome St,Carmine St & 6 Ave,-73.992663,40.718939,-74.002150,40.730386,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
13212,NaN,Subscriber,NaN,1,1972.0,15781,478,520,697,46182,11 Ave & W 41 St,W 52 St & 5 Ave,-73.998842,40.760301,-73.976485,40.759923,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
13213,NaN,Subscriber,NaN,1,1988.0,15081,471,467,1703,46183,Grand St & Havemeyer St,Dean St & 4 Ave,-73.956981,40.712868,-73.978951,40.683125,2015-02-08 00:23:00+00,2015-02-07 23:54:00+00
13214,NaN,Subscriber,NaN,1,1983.0,21672,247,479,922,46184,Perry St & Bleecker St,9 Ave & W 45 St,-74.004831,40.735354,-73.991255,40.760193,2015-02-08 00:10:00+00,2015-02-07 23:54:00+00
13215,NaN,Subscriber,NaN,1,1970.0,16336,488,457,849,46185,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
13216,NaN,Subscriber,NaN,1,1973.0,21609,488,457,826,46186,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
13217,NaN,Subscriber,NaN,1,1964.0,19470,3002,328,473,46187,South End Ave & Liberty St,Watts St & Greenwich St,-74.015756,40.711512,-74.009660,40.724055,2015-02-08 00:02:00+00,2015-02-07 23:54:00+00
13218,NaN,Subscriber,NaN,1,1960.0,18167,450,510,332,46188,W 49 St & 8 Ave,W 51 St & 6 Ave,-73.987882,40.762272,-73.980420,40.760660,2015-02-07 23:59:00+00,2015-02-07 23:54:00+00
13219,NaN,Subscriber,NaN,1,1987.0,15929,404,382,456,46189,9 Ave & W 14 St,University Pl & E 14 St,-74.005509,40.740583,-73.992005,40.734927,2015-02-08 00:03:00+00,2015-02-07 23:55:00+00
13220,NaN,Subscriber,NaN,1,1983.0,17541,466,254,327,46190,W 25 St & 6 Ave,W 11 St & 6 Ave,-73.991449,40.743954,-73.998004,40.735324,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
13221,NaN,Subscriber,NaN,2,1983.0,14736,494,116,306,46191,W 26 St & 8 Ave,W 17 St & 8 Ave,-73.997236,40.747348,-74.001497,40.741776,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
13222,NaN,Subscriber,NaN,1,1984.0,16300,432,495,1248,46192,E 7 St & Avenue A,W 47 St & 10 Ave,-73.983799,40.726218,-73.993012,40.762699,2015-02-08 00:17:00+00,2015-02-07 23:56:00+00
13223,NaN,Subscriber,NaN,1,1959.0,16978,325,152,1165,46193,E 19 St & 3 Ave,Warren St & Church St,-73.984738,40.736245,-74.009106,40.714740,2015-02-08 00:15:00+00,2015-02-07 23:56:00+00
13224,NaN,Subscriber,NaN,1,1974.0,16722,295,461,993,46194,Pike St & E Broadway,E 20 St & 2 Ave,-73.992939,40.714067,-73.982050,40.735877,2015-02-08 00:13:00+00,2015-02-07 23:56:00+00
13225,NaN,Subscriber,NaN,2,1960.0,20184,265,455,1422,46195,Stanton St & Chrystie St,1 Ave & E 44 St,-73.991475,40.722293,-73.969053,40.750020,2015-02-08 00:20:00+00,2015-02-07 23:57:00+00
13226,NaN,Subscriber,NaN,1,1953.0,15585,325,470,689,46196,E 19 St & 3 Ave,W 20 St & 8 Ave,-73.984738,40.736245,-74.000040,40.743453,2015-02-08 00:08:00+00,2015-02-07 23:57:00+00
13227,NaN,Subscriber,NaN,2,1986.0,16395,325,474,428,46197,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:04:00+00,2015-02-07 23:57:00+00
13228,NaN,Subscriber,NaN,1,1986.0,15545,325,474,392,46198,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:03:00+00,2015-02-07 23:57:00+00
13229,NaN,Subscriber,NaN,2,1983.0,19540,334,368,548,46199,W 20 St & 7 Ave,Carmine St & 6 Ave,-73.997262,40.742388,-74.002150,40.730386,2015-02-08 00:08:00+00,2015-02-07 23:58:00+00
13230,NaN,Subscriber,NaN,2,1965.0,20998,417,439,917,46200,Barclay St & Church St,E 4 St & 2 Ave,-74.010202,40.712912,-73.989780,40.726281,2015-02-08 00:15:00+00,2015-02-07 23:59:00+00

In [14]:
task2_3 = '''
SELECT AVG(tripduration) as avg_weekends FROM citibike
WHERE extract(DOW FROM starttime) in (0,6) 
'''
pd.read_csv(IO(queryCartoDB(task2_3)), sep=',')

   avg_weekends  Unnamed: 1
0    662.942181         NaN

### The average trip duration during weekends is 663 seconds, i.e. 10.05 mins.

## Selecting trips started on the weekdays
- What are average trip duration during weekdays?

In [15]:
task2_4 = '''
SELECT * FROM citibike
WHERE extract(DOW FROM starttime) NOT IN (0,6) 
'''
pd.read_csv(IO(queryCartoDB(task2_4)), sep=',')

,the_geom,usertype,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,cartodb_id,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,NaN,Subscriber,NaN,1,1971.0,17575,488,167,643,9806,W 39 St & 9 Ave,E 39 St & 3 Ave,-73.993722,40.756458,-73.976049,40.748901,2015-02-03 14:50:00+00,2015-02-03 14:39:00+00
1,NaN,Subscriber,NaN,1,1973.0,20313,440,332,1379,13113,E 45 St & 3 Ave,Cherry St,-73.972826,40.752554,-73.979481,40.712199,2015-02-04 07:30:00+00,2015-02-04 07:07:00+00
2,NaN,Subscriber,NaN,1,1992.0,20684,489,442,199,6442,10 Ave & W 28 St,W 27 St & 7 Ave,-74.001768,40.750664,-73.993915,40.746647,2015-02-02 00:05:00+00,2015-02-02 00:02:00+00
3,NaN,Subscriber,NaN,2,1964.0,16094,349,326,418,6443,Rivington St & Ridge St,E 11 St & 1 Ave,-73.983299,40.718502,-73.984267,40.729538,2015-02-02 00:10:00+00,2015-02-02 00:03:00+00
4,NaN,Subscriber,NaN,1,1974.0,17362,415,279,276,6444,Pearl St & Hanover Square,Peck Slip & Front St,-74.009260,40.704718,-74.001670,40.707873,2015-02-02 00:09:00+00,2015-02-02 00:04:00+00
5,NaN,Subscriber,NaN,2,1992.0,15475,237,496,420,6445,E 11 St & 2 Ave,E 16 St & 5 Ave,-73.986724,40.730473,-73.992390,40.737262,2015-02-02 00:13:00+00,2015-02-02 00:06:00+00
6,NaN,Subscriber,NaN,1,1968.0,16272,450,477,304,6446,W 49 St & 8 Ave,W 41 St & 8 Ave,-73.987882,40.762272,-73.990026,40.756405,2015-02-02 00:12:00+00,2015-02-02 00:07:00+00
7,NaN,Subscriber,NaN,1,1979.0,16370,391,467,622,6447,Clark St & Henry St,Dean St & 4 Ave,-73.993446,40.697601,-73.978951,40.683125,2015-02-02 00:18:00+00,2015-02-02 00:08:00+00
8,NaN,Subscriber,NaN,1,1963.0,19437,482,434,371,6448,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 00:15:00+00,2015-02-02 00:09:00+00
9,NaN,Subscriber,NaN,1,1982.0,21211,2008,330,477,6449,Little West St & 1 Pl,Reade St & Broadway,-74.016777,40.705693,-74.005628,40.714505,2015-02-02 00:19:00+00,2015-02-02 00:11:00+00
10,NaN,Subscriber,NaN,2,1978.0,21417,423,521,743,6450,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-02 00:25:00+00,2015-02-02 00:12:00+00
11,NaN,Subscriber,NaN,1,1956.0,15722,453,504,599,6451,W 22 St & 8 Ave,1 Ave & E 15 St,-73.999154,40.744751,-73.981656,40.732219,2015-02-02 00:22:00+00,2015-02-02 00:12:00+00
12,NaN,Subscriber,NaN,1,1962.0,18972,236,285,345,6452,St Marks Pl & 2 Ave,Broadway & E 14 St,-73.987140,40.728419,-73.990741,40.734546,2015-02-02 00:18:00+00,2015-02-02 00:12:00+00
13,NaN,Subscriber,NaN,1,1980.0,19628,476,301,721,6453,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-02 00:25:00+00,2015-02-02 00:13:00+00
14,NaN,Subscriber,NaN,1,1978.0,15169,376,279,182,6454,John St & William St,Peck Slip & Front St,-74.007222,40.708621,-74.001670,40.707873,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
15,NaN,Subscriber,NaN,1,1997.0,17533,411,342,154,6455,E 6 St & Avenue D,Columbia St & Rivington St,-73.976687,40.722281,-73.980166,40.717400,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
16,NaN,Subscriber,NaN,1,1983.0,19761,491,470,435,6456,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-02 00:21:00+00,2015-02-02 00:14:00+00
17,NaN,Subscriber,NaN,1,1993.0,17267,393,236,310,6457,E 5 St & Avenue C,St Marks Pl & 2 Ave,-73.979955,40.722992,-73.987140,40.728419,2015-02-02 00:20:00+00,2015-02-02 00:15:00+00
18,NaN,Subscriber,NaN,1,1964.0,18691,470,470,1274,6458,W 20 St & 8 Ave,W 20 St & 8 Ave,-74.000040,40.743453,-74.000040,40.743453,2015-02-02 00:37:00+00,2015-02-02 00:16:00+00
19,NaN,Subscriber,NaN,1,1977.0,17106,174,485,642,6459,E 25 St & 1 Ave,W 37 St & 5 Ave,-73.977387,40.738177,-73.983390,40.750380,2015-02-02 00:29:00+00,2015-02-02 00:18:00+00
20,NaN,Subscriber,NaN,1,1973.0,20009,483,345,256,6460,E 12 St & 3 Ave,W 13 St & 6 Ave,-73.988900,40.732233,-73.997044,40.736494,2015-02-02 00:22:00+00,2015-02-02 00:18:00+00
21,NaN,Subscriber,NaN,1,1979.0,18777,442,489,334,6461,W 27 St & 7 Ave,10 Ave & W 28 St,-73.993915,40.746647,-74.001768,40.750664,2015-02-02 00:25:00+00,2015-02-02 00:19:00+00
22,NaN,Subscriber,NaN,1,1989.0,15357,174,507,90,6462,E 25 St & 1 Ave,E 25 St & 2 Ave,-73.977387,40.738177,-73.979738,40.739126,2015-02-02 00:20:00+00,2015-02-02 00:19:00+00
23,NaN,Subscriber,NaN,1,1983.0,18487,405,380,203,6463,Washington St & Gansevoort St,W 4 St & 7 Ave S,-74.008119,40.739323,-74.002939,40.734011,2015-02-02 00:23:00+00,2015-02-02 00:20:00+00
24,NaN,Subscriber,NaN,1,1981.0,20863,439,334,649,6464,E 4 St & 2 Ave,W 20 St & 7 Ave,-73.989780,40.726281,-73.997262,40.742388,2015-02-02 00:32:00+00,2015-02-02 00:22:00+00
25,NaN,Subscriber,NaN,1,1970.0,16539,448,508,319,6465,W 37 St & 10 Ave,W 46 St & 11 Ave,-73.997901,40.756604,-73.996674,40.763414,2015-02-02 00:29:00+00,2015-02-02 00:23:00+00
26,NaN,Subscriber,NaN,1,1961.0,18737,301,428,154,6466,E 2 St & Avenue B,E 3 St & 1 Ave,-73.983688,40.722174,-73.987834,40.724677,2015-02-02 00:30:00+00,2015-02-02 00:27:00+00
27,NaN,Subscriber,NaN,2,1980.0,17797,195,331,550,6467,Liberty St & Broadway,Pike St & Monroe St,-74.010434,40.709056,-73.991930,40.711731,2015-02-02 00:37:00+00,2015-02-02 00:28:00+00
28,NaN,Subscriber,NaN,1,1990.0,20638,478,529,268,6468,11 Ave & W 41 St,W 42 St & 8 Ave,-73.998842,40.760301,-73.990985,40.757570,2015-02-02 00:34:00+00,2015-02-02 00:29:00+00
29,NaN,Subscriber,NaN,1,1989.0,17636,366,421,153,6469,Clinton Ave & Myrtle Ave,Clermont Ave & Park Ave,-73.968896,40.693261,-73.971297,40.695734,2015-02-02 00:31:00+00,2015-02-02 00:29:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32939,NaN,Subscriber,NaN,1,1957.0,18249,492,465,321,39381,W 33 St & 7 Ave,Broadway & W 41 St,-73.990931,40.750200,-73.986580,40.755136,2015-02-06 23:52:00+00,2015-02-06 23:47:00+00
32940,NaN,Subscriber,NaN,2,1972.0,19146,318,523,449,39382,E 43 St & Vanderbilt Ave,W 38 St & 8 Ave,-73.977987,40.753202,-73.991382,40.754666,2015-02-06 23:55:00+00,2015-02-06 23:48:00+00
32941,NaN,Subscriber,NaN,1,1984.0,15313,434,509,120,39383,9 Ave & W 18 St,9 Ave & W 22 St,-74.003664,40.743174,-74.001971,40.745497,2015-02-06 23:50:00+00,2015-02-06 23:48:00+00
32942,NaN,Subscriber,NaN,1,1979.0,18469,2002,274,977,39384,Wythe Ave & Metropolitan Ave,Lafayette Ave & Fort Greene Pl,-73.963198,40.716887,-73.976682,40.686919,2015-02-07 00:05:00+00,2015-02-06 23:49:00+00
32943,NaN,Subscriber,NaN,1,1966.0,18929,403,402,501,39385,E 2 St & 2 Ave,Broadway & E 22 St,-73.990697,40.725029,-73.989551,40.740343,2015-02-06 23:57:00+00,2015-02-06 23:49:00+00
32944,NaN,Subscriber,NaN,1,1987.0,19009,402,545,441,39386,Broadway & E 22 St,E 23 St & 1 Ave,-73.989551,40.740343,-73.978095,40.736502,2015-02-06 23:58:00+00,2015-02-06 23:50:00+00
32945,NaN,Subscriber,NaN,1,1984.0,17102,438,325,388,39387,St Marks Pl & 1 Ave,E 19 St & 3 Ave,-73.985649,40.727791,-73.984738,40.736245,2015-02-06 23:57:00+00,2015-02-06 23:50:00+00
32946,NaN,Subscriber,NaN,2,1972.0,18686,266,293,607,39388,Avenue D & E 8 St,Lafayette St & E 8 St,-73.975748,40.723684,-73.990765,40.730287,2015-02-07 00:01:00+00,2015-02-06 23:51:00+00
32947,NaN,Subscriber,NaN,1,1989.0,15377,472,402,284,39389,E 32 St & Park Ave,Broadway & E 22 St,-73.981948,40.745712,-73.989551,40.740343,2015-02-06 23:55:00+00,2015-02-06 23:51:00+00
32948,NaN,Subscriber,NaN,1,1984.0,17844,435,383,271,39390,W 21 St & 6 Ave,Greenwich Ave & Charles St,-73.994156,40.741740,-74.000271,40.735238,2015-02-06 23:56:00+00,2015-02-06 23:51:00+00
32949,NaN,Subscriber,NaN,1,1987.0,21040,438,361,572,39391,St Marks Pl & 1 Ave,Allen St & Hester St,-73.985649,40.727791,-73.991908,40.716059,2015-02-07 00:01:00+00,2015-02-06 23:52:00+00
32950,NaN,Subscriber,NaN,1,1981.0,19480,380,503,498,39392,W 4 St & 7 Ave S,E 20 St & Park Ave,-74.002939,40.734011,-73.987520,40.738274,2015-02-07 00:01:00+00,2015-02-06 23:53:00+00
32951,NaN,Subscriber,NaN,1,1978.0,21130,258,324,425,39393,DeKalb Ave & Vanderbilt Ave,DeKalb Ave & Hudson Ave,-73.968855,40.689407,-73.981013,40.689888,2015-02-07 00:00:00+00,2015-02-06 23:53:00+00
32952,NaN,Subscriber,NaN,1,1983.0,16934,435,496,267,39394,W 21 St & 6 Ave,E 16 St & 5 Ave,-73.994156,40.741740,-73.992390,40.737262,2015-02-06 23:58:00+00,2015-02-06 23:53:00+00
32953,NaN,Subscriber,NaN,1,1968.0,20745,318,484,165,39395,E 43 St & Vanderbilt Ave,W 44 St & 5 Ave,-73.977987,40.753202,-73.980144,40.755003,2015-02-06 23:56:00+00,2015-02-06 23:53:00+00
32954,NaN,Subscriber,NaN,1,1969.0,16811,507,464,751,39396,E 25 St & 2 Ave,E 56 St & 3 Ave,-73.979738,40.739126,-73.967597,40.759345,2015-02-07 00:06:00+00,2015-02-06 23:54:00+00
32955,NaN,Subscriber,NaN,1,1980.0,21259,476,301,747,39397,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-07 00:07:00+00,2015-02-06 23:54:00+00
32956,NaN,Subscriber,NaN,1,1993.0,15618,375,439,511,39398,Mercer St & Bleecker St,E 4 St & 2 Ave,-73.996951,40.726795,-73.989780,40.726281,2015-02-07 00:03:00+00,2015-02-06 23:54:00+00
32957,NaN,Subscriber,NaN,1,1959.0,17370,486,497,489,39399,Broadway & W 29 St,E 17 St & Broadway,-73.988557,40.746201,-73.990093,40.737050,2015-02-07 00:02:00+00,2015-02-06 23:54:00+00
32958,NaN,Subscriber,NaN,1,1984.0,19430,295,504,1183,39400,Pike St & E Broadway,1 Ave & E 15 St,-73.992939,40.714067,-73.981656,40.732219,2015-02-07 00:14:00+00,2015-02-06 23:55:00+00
32959,NaN,Subscriber,NaN,1,1986.0,18303,512,510,649,39401,W 29 St & 9 Ave,W 51 St & 6 Ave,-73.998393,40.750073,-73.980420,40.760660,2015-02-07 00:06:00+00,2015-02-06 23:55:00+00
32960,NaN,Subscriber,NaN,1,1990.0,20360,453,254,377,39402,W 22 St & 8 Ave,W 11 St & 6 Ave,-73.999154,40.744751,-73.998004,40.735324,2015-02-07 00:01:00+00,2015-02-06 23:55:00+00
32961,NaN,Subscriber,NaN,1,1983.0,21564,491,470,485,39403,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-07 00:04:00+00,2015-02-06 23:56:00+00
32962,NaN,Subscriber,NaN,1,1983.0,21575,368,482,298,39404,Carmine St & 6 Ave,W 15 St & 7 Ave,-74.002150,40.730386,-73.999318,40.739355,2015-02-07 00:01:00+00,2015-02-06 23:56:00+00
32963,NaN,Subscriber,NaN,1,1983.0,21014,346,461,648,39405,Bank St & Hudson St,E 20 St & 2 Ave,-74.006180,40.736529,-73.982050,40.735877,2015-02-07 00:07:00+00,2015-02-06 23:57:00+00
32964,NaN,Subscriber,NaN,2,1989.0,17797,450,252,1261,39406,W 49 St & 8 Ave,MacDougal St & Washington Sq,-73.987882,40.762272,-73.998522,40.732264,2015-02-07 00:19:00+00,2015-02-06 23:58:00+00
32965,NaN,Subscriber,NaN,1,1984.0,16975,270,324,331,39407,Adelphi St & Myrtle Ave,DeKalb Ave & Hudson Ave,-73.971789,40.693083,-73.981013,40.689888,2015-02-07 00:04:00+00,2015-02-06 23:58:00+00
32966,NaN,Subscriber,NaN,1,1982.0,19820,236,345,629,39408,St Marks Pl & 2 Ave,W 13 St & 6 Ave,-73.987140,40.728419,-73.997044,40.736494,2015-02-07 00:10:00+00,2015-02-06 23:59:00+00
32967,NaN,Subscriber,NaN,1,1966.0,19487,502,263,492,39409,Henry St & Grand St,Elizabeth St & Hester St,-73.981346,40.714215,-73.996375,40.717290,2015-02-07 00:07:00+00,2015-02-06 23:59:00+00
32968,NaN,Subscriber,NaN,1,1987.0,15426,301,401,329,39410,E 2 St & Avenue B,Allen St & Rivington St,-73.983688,40.722174,-73.989978,40.720196,2015-02-07 00:04:00+00,2015-02-06 23:59:00+00

In [16]:
task2_5 = '''
SELECT AVG(tripduration) as avg_weekdays FROM citibike
WHERE extract(DOW FROM starttime) NOT IN (0,6) 
'''
pd.read_csv(IO(queryCartoDB(task2_5)), sep=',')

   avg_weekdays  Unnamed: 1
0    681.052292         NaN

### The average trip duration during weekdays is 681 seconds, i.e. 11.35 mins.

# Task 3 — Working with Space

## Showing the list of start station locations
- Using GROUP BY

In [17]:
task3_1 = '''
SELECT CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude, 
                                start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name 
FROM citibike
GROUP BY start_station_id, start_station_latitude, start_station_longitude
ORDER BY cartodb_id
'''
pd.read_csv(IO(queryCartoDB(task3_1)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name
0,0101000020110F000042FA2528026C5FC1F9B9029FFCFA...,1,8 Ave & W 31 St
1,0101000020110F0000B72236DE7E6B5FC1A5B36C6610F9...,2,E 17 St & Broadway
2,0101000020110F0000309ECD0FB7695FC14F41EB09FDFC...,3,Grand Army Plaza & Central Park S
3,0101000020110F0000262DCC7D156D5FC111F247CB3FF7...,4,6 Ave & Broome St
4,0101000020110F0000833ADCCB156B5FC1BEFBAE9CA7F2...,5,Lawrence St & Willoughby St
5,0101000020110F0000C12D0F658D675FC1323CC0ADCAF2...,6,Willoughby Ave & Walworth St
6,0101000020110F00006B6C9CBF186A5FC109C57CA0D8FC...,7,W 56 St & 6 Ave
7,0101000020110F00005A26772B766B5FC11C6CFDE484F7...,8,E 4 St & 2 Ave
8,0101000020110F0000F993EDE4EC6B5FC122E50B32EAF7...,9,Washington Pl & Broadway
9,0101000020110F00003D22E9FBDB6C5FC18DD337A658F9...,10,Greenwich Ave & 8 Ave
10,0101000020110F00002E1B9FF6466B5FC1E99EE4C5B6FA...,12,Broadway & W 32 St
11,0101000020110F0000049C1A69CE6C5FC1205139A81BF8...,13,Carmine St & 6 Ave
12,0101000020110F0000A87451BDDC6A5FC1EB7B4387FCF7...,14,E 11 St & 1 Ave
13,0101000020110F0000517121EA906B5FC182C0396DB4F8...,15,Broadway & E 14 St
14,0101000020110F0000047C4EA0256A5FC1D9059AB05DF7...,17,E 9 St & Avenue C
15,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,W 45 St & 6 Ave
16,0101000020110F0000C06D97808D6A5FC1BD39524AAEF7...,20,E 10 St & Avenue A
17,0101000020110F000091C14B01406B5FC1A3DCAD024AF7...,21,E 3 St & 1 Ave
18,0101000020110F00009F5AD0F883695FC18BD6351F95FB...,22,E 48 St & 3 Ave
19,0101000020110F0000E5C68C67566B5FC1CFC9ACC28AFD...,23,W 56 St & 10 Ave
20,0101000020110F0000303622AF5E6A5FC1A3EB11A85CF9...,24,E 25 St & 2 Ave
21,0101000020110F0000EC774642E56C5FC13DF29213A3F7...,26,MacDougal St & Prince St
22,0101000020110F00002EBB7FC3E96B5FC13578821125FB...,27,8 Ave & W 33 St
23,0101000020110F00001E76C09C296B5FC16ACD1485FCF5...,28,Clinton St & Grand St
24,0101000020110F0000EEE2EC99196C5FC100162DBD45F7...,29,Lafayette St & Jersey St
25,0101000020110F0000505A780E946A5FC1B7C653F55EF8...,30,1 Ave & E 15 St
26,0101000020110F00001154E295996A5FC10680C9DF44F7...,31,E 6 St & Avenue B
27,0101000020110F000042517D0A9F6A5FC15138BD50E5F8...,32,E 20 St & 2 Ave
28,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,W 41 St & 8 Ave
29,0101000020110F0000DCAA7863C66B5FC11BA5784D77F6...,35,Forsyth St & Broome St
...,...,...,...
297,0101000020110F000019F7C7B2096A5FC1F10194C3E0FB...,2433,E 48 St & Madison Ave
298,0101000020110F0000D387C368DE685FC193F25C8393FB...,2462,E 51 St & 1 Ave
299,0101000020110F0000E463F723266A5FC14F49CEE530FB...,2481,Pershing Square North
300,0101000020110F00000EDB1043D86A5FC1098E90170AF2...,2509,Bond St & Schermerhorn St
301,0101000020110F0000BAF51EEBD8695FC1C4553BF749F2...,2558,DeKalb Ave & S Portland Ave
302,0101000020110F000099F9690747695FC1D617A37CFAF1...,2577,Clermont Ave & Lafayette Ave
303,0101000020110F00008077AE3304685FC1A3E1631FF7F2...,2762,Franklin Ave & Myrtle Ave
304,0101000020110F0000F2F00227D6685FC1E3F0607ED0F1...,2941,Washington Ave & Greene Ave
305,0101000020110F0000DA5401006A6A5FC1177BC9DEA3FB...,3167,W 44 St & 5 Ave
306,0101000020110F0000B4B6D9A8FF695FC1B42BC0556EF1...,3237,Atlantic Ave & Fort Greene Pl
307,0101000020110F00009A6669876B695FC10D48A3FB82F4...,3353,Railroad Ave & Kay Ave
308,0101000020110F0000E2BF6C8A0D6E5FC1932920126AF4...,3617,Broadway & Battery Pl
309,0101000020110F0000BED1C0F782685FC1A805EBBA8EF5...,3645,S 3 St & Bedford Ave
310,0101000020110F00001C8FDEBEA46B5FC1F99BE632D1F3...,3700,Henry St & Poplar St
311,0101000020110F00005CB2E76C746B5FC16FC1B8F4BCF3...,3902,Cadman Plaza E & Red Cross Pl
312,0101000020110F00007D0BEFFB916C5FC19358D78D8DF2...,4252,Atlantic Ave & Furman St
313,0101000020110F0000C5124F78DA695FC19387858CA7FB...,4267,E 47 St & Park Ave
314,0101000020110F000013E67A93D76D5FC1E085DF0946F4...,4308,Broad St & Bridge St
315,0101000020110F0000A8AED80FD6675FC123D0DAC368F2...,4544,DeKalb Ave & Skillman St
316,0101000020110F000097C9A809E76B5FC15DF6A6B925F4...,4666,Old Fulton St
317,0101000020110F000052716DFB7B6D5FC1634AEE724BF4...,5444,Old Slip & Front St
318,0101000020110F000029BF3029796A5FC13B53193685F3...,5816,Nassau St & Navy St
319,0101000020110F00006F1B0D7971695FC1AA39F250F4FA...,7030,E 43 St & 2 Ave
320,0101000020110F00007B70CCAF376B5FC1099854822BFB...,7544,Broadway & W 37 St
321,0101000020110F0000262E4F4BAF6A5FC18F9D963E1FF2...,7628,Hanover Pl & Livingston St
322,0101000020110F0000C8A0F7054C695FC137B64E5D74F3...,8681,Clinton Ave & Flushing Ave
323,0101000020110F00007392D1EEBD685FC17A448F6F1AF2...,8955,Lafayette Ave & St James Pl
324,0101000020110F00006542E56C806B5FC1C60A924D2CF3...,9072,Cadman Plaza E & Tillary St
325,0101000020110F000099C8C5C42A6B5FC11224185D5BF2...,9886,Gallatin Pl & Livingston St
326,0101000020110F000084335DF3636A5FC130D056A6B7F3...,16606,Sands St & Navy St

## Showing the number of trips started per station

In [18]:
task3_2 = '''
SELECT CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude, 
                        start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name,
       COUNT(cartodb_id) as number_trips
FROM citibike
GROUP BY start_station_id, start_station_latitude, start_station_longitude
ORDER BY cartodb_id
'''
pd.read_csv(IO(queryCartoDB(task3_2)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name,number_trips
0,0101000020110F000042FA2528026C5FC1F9B9029FFCFA...,1,8 Ave & W 31 St,530
1,0101000020110F0000B72236DE7E6B5FC1A5B36C6610F9...,2,E 17 St & Broadway,455
2,0101000020110F0000309ECD0FB7695FC14F41EB09FDFC...,3,Grand Army Plaza & Central Park S,146
3,0101000020110F0000262DCC7D156D5FC111F247CB3FF7...,4,6 Ave & Broome St,112
4,0101000020110F0000833ADCCB156B5FC1BEFBAE9CA7F2...,5,Lawrence St & Willoughby St,60
5,0101000020110F0000C12D0F658D675FC1323CC0ADCAF2...,6,Willoughby Ave & Walworth St,27
6,0101000020110F00006B6C9CBF186A5FC109C57CA0D8FC...,7,W 56 St & 6 Ave,164
7,0101000020110F00005A26772B766B5FC11C6CFDE484F7...,8,E 4 St & 2 Ave,180
8,0101000020110F0000F993EDE4EC6B5FC122E50B32EAF7...,9,Washington Pl & Broadway,222
9,0101000020110F00003D22E9FBDB6C5FC18DD337A658F9...,10,Greenwich Ave & 8 Ave,342
10,0101000020110F00002E1B9FF6466B5FC1E99EE4C5B6FA...,12,Broadway & W 32 St,230
11,0101000020110F0000049C1A69CE6C5FC1205139A81BF8...,13,Carmine St & 6 Ave,238
12,0101000020110F0000A87451BDDC6A5FC1EB7B4387FCF7...,14,E 11 St & 1 Ave,191
13,0101000020110F0000517121EA906B5FC182C0396DB4F8...,15,Broadway & E 14 St,373
14,0101000020110F0000047C4EA0256A5FC1D9059AB05DF7...,17,E 9 St & Avenue C,201
15,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,W 45 St & 6 Ave,141
16,0101000020110F0000C06D97808D6A5FC1BD39524AAEF7...,20,E 10 St & Avenue A,296
17,0101000020110F000091C14B01406B5FC1A3DCAD024AF7...,21,E 3 St & 1 Ave,199
18,0101000020110F00009F5AD0F883695FC18BD6351F95FB...,22,E 48 St & 3 Ave,120
19,0101000020110F0000E5C68C67566B5FC1CFC9ACC28AFD...,23,W 56 St & 10 Ave,140
20,0101000020110F0000303622AF5E6A5FC1A3EB11A85CF9...,24,E 25 St & 2 Ave,267
21,0101000020110F0000EC774642E56C5FC13DF29213A3F7...,26,MacDougal St & Prince St,247
22,0101000020110F00002EBB7FC3E96B5FC13578821125FB...,27,8 Ave & W 33 St,387
23,0101000020110F00001E76C09C296B5FC16ACD1485FCF5...,28,Clinton St & Grand St,81
24,0101000020110F0000EEE2EC99196C5FC100162DBD45F7...,29,Lafayette St & Jersey St,289
25,0101000020110F0000505A780E946A5FC1B7C653F55EF8...,30,1 Ave & E 15 St,397
26,0101000020110F00001154E295996A5FC10680C9DF44F7...,31,E 6 St & Avenue B,191
27,0101000020110F000042517D0A9F6A5FC15138BD50E5F8...,32,E 20 St & 2 Ave,296
28,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,W 41 St & 8 Ave,507
29,0101000020110F0000DCAA7863C66B5FC11BA5784D77F6...,35,Forsyth St & Broome St,212
...,...,...,...,...
297,0101000020110F000019F7C7B2096A5FC1F10194C3E0FB...,2433,E 48 St & Madison Ave,153
298,0101000020110F0000D387C368DE685FC193F25C8393FB...,2462,E 51 St & 1 Ave,55
299,0101000020110F0000E463F723266A5FC14F49CEE530FB...,2481,Pershing Square North,323
300,0101000020110F00000EDB1043D86A5FC1098E90170AF2...,2509,Bond St & Schermerhorn St,54
301,0101000020110F0000BAF51EEBD8695FC1C4553BF749F2...,2558,DeKalb Ave & S Portland Ave,33
302,0101000020110F000099F9690747695FC1D617A37CFAF1...,2577,Clermont Ave & Lafayette Ave,25
303,0101000020110F00008077AE3304685FC1A3E1631FF7F2...,2762,Franklin Ave & Myrtle Ave,9
304,0101000020110F0000F2F00227D6685FC1E3F0607ED0F1...,2941,Washington Ave & Greene Ave,21
305,0101000020110F0000DA5401006A6A5FC1177BC9DEA3FB...,3167,W 44 St & 5 Ave,137
306,0101000020110F0000B4B6D9A8FF695FC1B42BC0556EF1...,3237,Atlantic Ave & Fort Greene Pl,36
307,0101000020110F00009A6669876B695FC10D48A3FB82F4...,3353,Railroad Ave & Kay Ave,7
308,0101000020110F0000E2BF6C8A0D6E5FC1932920126AF4...,3617,Broadway & Battery Pl,103
309,0101000020110F0000BED1C0F782685FC1A805EBBA8EF5...,3645,S 3 St & Bedford Ave,13
310,0101000020110F00001C8FDEBEA46B5FC1F99BE632D1F3...,3700,Henry St & Poplar St,18
311,0101000020110F00005CB2E76C746B5FC16FC1B8F4BCF3...,3902,Cadman Plaza E & Red Cross Pl,18
312,0101000020110F00007D0BEFFB916C5FC19358D78D8DF2...,4252,Atlantic Ave & Furman St,5
313,0101000020110F0000C5124F78DA695FC19387858CA7FB...,4267,E 47 St & Park Ave,226
314,0101000020110F000013E67A93D76D5FC1E085DF0946F4...,4308,Broad St & Bridge St,36
315,0101000020110F0000A8AED80FD6675FC123D0DAC368F2...,4544,DeKalb Ave & Skillman St,10
316,0101000020110F000097C9A809E76B5FC15DF6A6B925F4...,4666,Old Fulton St,14
317,0101000020110F000052716DFB7B6D5FC1634AEE724BF4...,5444,Old Slip & Front St,60
318,0101000020110F000029BF3029796A5FC13B53193685F3...,5816,Nassau St & Navy St,7
319,0101000020110F00006F1B0D7971695FC1AA39F250F4FA...,7030,E 43 St & 2 Ave,86
320,0101000020110F00007B70CCAF376B5FC1099854822BFB...,7544,Broadway & W 37 St,98
321,0101000020110F0000262E4F4BAF6A5FC18F9D963E1FF2...,7628,Hanover Pl & Livingston St,28
322,0101000020110F0000C8A0F7054C695FC137B64E5D74F3...,8681,Clinton Ave & Flushing Ave,17
323,0101000020110F00007392D1EEBD685FC17A448F6F1AF2...,8955,Lafayette Ave & St James Pl,32
324,0101000020110F00006542E56C806B5FC1C60A924D2CF3...,9072,Cadman Plaza E & Tillary St,22
325,0101000020110F000099C8C5C42A6B5FC11224185D5BF2...,9886,Gallatin Pl & Livingston St,7
326,0101000020110F000084335DF3636A5FC130D056A6B7F3...,16606,Sands St & Navy St,4

# Showing the number of trips started per station only for stations within 500m of Time Square! 
- The coordinates of Time Square is (40.7577,-73.9857)

In [19]:
task3_3 = '''
SELECT CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude, 
                                start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name,
       COUNT(cartodb_id) as number_trips
FROM citibike
WHERE ST_DWithin(CDB_LatLng(start_station_latitude, 
                    start_station_longitude)::geography,
                    CDB_LatLng(40.7577,-73.9857)::geography,500)
GROUP BY start_station_id, start_station_latitude, start_station_longitude
ORDER BY cartodb_id
'''
pd.read_csv(IO(queryCartoDB(task3_3)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name,number_trips
0,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,W 45 St & 6 Ave,141
1,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,W 41 St & 8 Ave,507
2,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,Broadway & W 49 St,213
3,0101000020110F000004AF971C1D6B5FC17A48F3C1A8FB...,54,Broadway & W 41 St,251
4,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,W 45 St & 8 Ave,141
5,0101000020110F00003F9300B2976B5FC1B8B88F3102FC...,783,W 42 St & 8 Ave,221
6,0101000020110F0000F22A632FBE6A5FC1363A28CFADFB...,1115,W 43 St & 6 Ave,112

# Task 4 — Putting it all together

## Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare!

In [20]:
task4_1 = '''
SELECT CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude, 
                                start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name,
       AVG(tripduration) as average_trip_duration,
       COUNT(cartodb_id) as number_trips
FROM citibike
WHERE ST_DWithin(CDB_LatLng(start_station_latitude, 
                    start_station_longitude)::geography,
                    CDB_LatLng(40.7577,-73.9857)::geography,500) 
                    AND extract(DOW FROM starttime) in (0, 6)
GROUP BY start_station_id, start_station_latitude, start_station_longitude
ORDER BY average_trip_duration DESC
LIMIT 1
'''
pd.read_csv(IO(queryCartoDB(task4_1)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name,average_trip_duration,number_trips
0,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,Broadway & W 49 St,1010.104167,48

### Answer: Broadway & W 49 St is the station that had the longest average trip duration during weekends and within 500m of TimeSquare

## Extra: create lines for trips started from stations within 500m of Times Squares and lasted less than 2 hours. The number of trips per each pair of stations are output as attributes of these lines.

In [21]:
task4_2 = '''
SELECT MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name,
       MIN(end_station_name) as end_station_name,
       COUNT(cartodb_id) as number_trips,
       AVG(tripduration) as average_trip_duration      
FROM citibike
WHERE ST_DWithin(CDB_LatLng(start_station_latitude, 
                    start_station_longitude)::geography,
                    CDB_LatLng(40.7577,-73.9857)::geography,500) 
      AND tripduration <= 7200
GROUP BY start_station_id, start_station_latitude, start_station_longitude, 
            end_station_id, end_station_latitude, end_station_longitude

'''
pd.read_csv(IO(queryCartoDB(task4_2)), sep=',')

,cartodb_id,start_station_name,end_station_name,number_trips,average_trip_duration
0,18466,Broadway & W 49 St,2 Ave & E 31 St,2,693.000000
1,2226,W 41 St & 8 Ave,W 21 St & 6 Ave,2,895.500000
2,15621,Broadway & W 41 St,E 48 St & Madison Ave,2,414.500000
3,34734,W 45 St & 6 Ave,W 29 St & 9 Ave,1,700.000000
4,37006,W 43 St & 6 Ave,W 52 St & 11 Ave,1,1086.000000
5,6007,Broadway & W 41 St,W 24 St & 7 Ave,3,444.000000
6,20272,W 43 St & 6 Ave,E 37 St & Lexington Ave,4,365.250000
7,11540,W 45 St & 8 Ave,W 20 St & 11 Ave,3,899.333333
8,13614,W 45 St & 6 Ave,W 27 St & 7 Ave,3,457.666667
9,39800,W 41 St & 8 Ave,Elizabeth St & Hester St,1,1362.000000
10,29033,Broadway & W 41 St,Cherry St,1,2217.000000
11,45442,Broadway & W 49 St,W 45 St & 6 Ave,1,1251.000000
12,14181,W 45 St & 6 Ave,E 51 St & 1 Ave,2,921.000000
13,959,W 45 St & 8 Ave,W 47 St & 10 Ave,4,243.500000
14,7889,W 42 St & 8 Ave,E 47 St & 2 Ave,2,743.000000
15,7076,W 45 St & 6 Ave,W 41 St & 8 Ave,12,269.333333
16,33533,W 45 St & 8 Ave,E 40 St & 5 Ave,1,414.000000
17,34712,Broadway & W 41 St,W 11 St & 6 Ave,1,658.000000
18,13230,W 42 St & 8 Ave,W 59 St & 10 Ave,5,816.600000
19,4507,W 41 St & 8 Ave,Greenwich Ave & 8 Ave,2,837.500000
20,13031,W 41 St & 8 Ave,E 43 St & Vanderbilt Ave,31,449.290323
21,17712,W 43 St & 6 Ave,W 43 St & 10 Ave,1,339.000000
22,34501,W 45 St & 6 Ave,11 Ave & W 41 St,1,465.000000
23,9844,W 41 St & 8 Ave,Broadway & W 41 St,2,213.500000
24,356,W 41 St & 8 Ave,W 33 St & 7 Ave,5,290.200000
25,10223,Broadway & W 41 St,Broadway & W 24 St,5,525.200000
26,25199,W 41 St & 8 Ave,Broadway & W 51 St,2,340.000000
27,2536,W 45 St & 8 Ave,W 51 St & 6 Ave,2,327.500000
28,37521,W 41 St & 8 Ave,10 Ave & W 28 St,1,574.000000
29,19530,W 41 St & 8 Ave,Broadway & W 29 St,4,441.750000
...,...,...,...,...,...
542,22083,W 42 St & 8 Ave,E 53 St & Lexington Ave,3,690.000000
543,34099,Broadway & W 49 St,W 46 St & 11 Ave,2,466.000000
544,7354,Broadway & W 49 St,Lexington Ave & E 24 St,1,984.000000
545,16753,W 45 St & 6 Ave,W 43 St & 10 Ave,4,361.750000
546,21315,Broadway & W 49 St,South End Ave & Liberty St,1,1823.000000
547,38470,W 43 St & 6 Ave,11 Ave & W 41 St,1,434.000000
548,30699,W 41 St & 8 Ave,Warren St & Church St,1,1535.000000
549,12092,Broadway & W 41 St,E 16 St & 5 Ave,3,730.000000
550,12625,W 45 St & 6 Ave,Broadway & W 58 St,1,760.000000
551,22819,W 45 St & 8 Ave,E 55 St & Lexington Ave,1,824.000000
552,8767,Broadway & W 41 St,E 33 St & 2 Ave,3,726.333333
553,14978,W 45 St & 6 Ave,W 45 St & 8 Ave,3,229.000000
554,7686,Broadway & W 41 St,E 20 St & 2 Ave,6,913.000000
555,6699,W 42 St & 8 Ave,W 45 St & 6 Ave,1,308.000000
556,17638,W 41 St & 8 Ave,Washington Square E,1,1153.000000
557,28510,W 43 St & 6 Ave,W 27 St & 7 Ave,2,625.500000
558,17023,W 45 St & 6 Ave,E 14 St & Avenue B,1,2551.000000
559,3105,W 45 St & 6 Ave,E 37 St & Lexington Ave,6,1249.666667
560,13485,Broadway & W 49 St,E 47 St & 2 Ave,4,697.250000
561,13694,W 41 St & 8 Ave,Pearl St & Hanover Square,3,2301.000000
562,2329,W 41 St & 8 Ave,W 49 St & 8 Ave,8,316.625000
563,5582,W 42 St & 8 Ave,W 25 St & 6 Ave,2,892.500000
564,12873,W 41 St & 8 Ave,11 Ave & W 59 St,3,622.000000
565,17983,W 43 St & 6 Ave,W 29 St & 9 Ave,2,869.000000
566,22345,W 45 St & 8 Ave,W 52 St & 5 Ave,1,459.000000
567,27219,Broadway & W 49 St,W 59 St & 10 Ave,2,443.500000
568,7341,W 45 St & 8 Ave,8 Ave & W 33 St,10,423.500000
569,8971,W 42 St & 8 Ave,Broadway & W 37 St,1,357.000000
570,36545,W 43 St & 6 Ave,W 41 St & 8 Ave,1,252.000000
571,18854,Broadway & W 41 St,E 10 St & 5 Ave,1,966.000000

## ASH Score 100. Extra Credit 100

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel